### ISSUE TITLE
wuaueng.dll

### ISSUE THREAD

**Issue by akuma122** [zeffy/wufuc#104]
file wuaueng.dll is under the minimum supported version 
win7x64 pro sp1 clean build

**Comment by zeffy** [comment]
You need to install updates through Windows Update until the "unsupported hardware" pop-up displays, then run the installer again; it will work once you do that.

**Comment by akuma122** [comment]
Yeah I built windows they it did 22 updates which is when the pop up appeared, went through your blog and removed the kb that you listed and repeated until all pdatesbinstalled then ran your app

Sent from my Windows 10 phone

**Comment by zeffy** [comment]
You shouldn't have to remove any updates. Just install wufuc after the unsupported hardware window pops up, and everything should be working normally--no pop up window, and updates will continue installing as usual.
