### ISSUE TITLE
Wufuc no longer working since last night's Windows Update

### ISSUE THREAD

**Issue by Moltresrider** [zeffy/wufuc#105]
on that Sandy Bridge laptop, I am getting "Unsupported hardware" again since the update last night and wufuc is not working

**Comment by swshan** [comment]
It seems newer version had this problem too.

**Comment by zeffy** [comment]
Still works for me, so I'm going to assume this the same issue as #98. This will no longer be an issue once I release v0.8. No ETA on that yet though, unfortunately; I've been working very hard to make sure every single known issue is fixed before I release it.

Going to close this for now though, unless either of you have further information that would set this issue apart from #98.
