### ISSUE TITLE
Reboot loop

### ISSUE THREAD

**Issue by Enteneller2017** [zeffy/wufuc#106]
I'm trying to run an i3-7100 on an MSI B250.

I've installed Win7 Home Premium SP1 to the first partition of the SSD and ran all the 'important' updates, then patched it with wufuc_setup_x64.msi. Done so without errors on my old machine (Athlon II X2, ASRock 785GM). 

The B250-i3 machine (a second SSD with Linux-only (also BIOS) and Grub) lets me boot into Win7 initially, then after 2 seconds it stops and reboots (while the colours of the windows icon commence forming). After that the win installation offers to "start windows normally" or start a repair tool (which runs through, can't be cancelled and has no effect). Removing the Linux-only-SSD with Grub and booting solely from the Windows-SSD doesn't change the booting process at all (other than not having Grub): it starts to display the Windows icon and reboots after 2-3 seconds.

The setupact.log (C:\Windows\Panther) confirms BIOS mode for Win7. 
sha1sum of wuaueng.dll f24e24feffefe840b5d7ed20ebc99fb532831c30.
Using the stable version of wufuc.
When I partitioned the SSD I kept everything to BIOS, partition table selected in GParted was msdos. [wufuclogs.zip](https://github.com/zeffy/wufuc/files/1317482/wufuclogs.zip)

**Comment by zeffy** [comment]
That's really weird. Even while working with buggy development versions of wufuc, I've never outright crashed my PC. The worst it can do is crash several non-system critical services that will recover after a few minutes.

To determine if it is wufuc that is causing the issue, could you [boot into the Windows recovery environment](https://www.bleepingcomputer.com/tutorials/start-the-windows-7-recovery-environment/), open a Command prompt, and navigate to where you installed wufuc to and rename `wufuc.dll`:
```bat
Microsoft Windows [Version 6.1.7601]


X:\windows\system32> C:
C:\> cd "Program Files\wufuc"
C:\Program Files\wufuc> ren wufuc.dll wufuc.dll.bak
```

And then restart again and see what happens? Thanks.

If you're still boot looping after that, then I'd be inclined to think something else is most likely causing this.

**Comment by Enteneller2017** [comment]
Booted into the WRE on the old computer with the win7-SSD, renamed wufuc.dll, it rebooted just fine. 

Then without renaming it back I plugged the SSD into the Kabylake machine: same problem as before. System start repair win7 programme as before with "unable to start windows, this could be due to a recent change in hard- or software." It doesn't say anything about the cpu or certain hardware components. 

Any idea what could provoke the issue that early in the boot process? If only we could see what it loads while it forms those sprites for coloured windows icon.

**Comment by zeffy** [comment]
If you have some way to get into msconfig, you could try [turning on boot logging](http://www.techrepublic.com/blog/tr-dojo/monitor-windows-7-boot-logs-with-the-help-of-msconfig/), and check `ntbtlog.txt`. Other than that, I'm not really sure, tbh. Could it have something to do with secure boot or driver issues?

**Comment by Enteneller2017** [comment]
It was a driver issue indeed. Msi has a special tool called 'Smart Tool' to create a win7 boot stick, because it appears they have disabled something in the chipset by default so you can't install win7 from usb. Works flawlessly now. Thanks a lot for the hints!

**Comment by zeffy** [comment]
That's great! I'm glad you were able to fix it.
