### ISSUE TITLE
wufuc doesn't wokr anymore

### ISSUE THREAD

**Issue by nidman** [zeffy/wufuc#109]
After october MS updates wufuc stops working. The job in the sheduler runs correctly but the notification window starts to appears on user logon and during searching updates.
OS Windows7 SP1 x64

**Comment by zeffy** [comment]
There will be a new version out later this week that should fix this. In the meanwhile you can try uninstalling and reinstalling wufuc, that seems to have fixed it temporarily for some people.

**Comment by Shinji200** [comment]
It didn't work for me, I'm on Windows 8.1 x64, let´s hope the new update can fix the issue, anyways thanks a lot zeffy for your great work!

**Comment by zeffy** [comment]
@Shinji200 @nidman  v0.8 has been released, it should resolve any of the issues you were experiencing https://github.com/zeffy/wufuc/releases/latest
