### ISSUE TITLE
Getting multiple errors when deploying 

### ISSUE THREAD

**Issue by smith581** [zeffy/wufuc#110]
![img_5831](https://user-images.githubusercontent.com/10013955/31410225-fc40fc4e-adc2-11e7-8333-cede3834e340.jpg)
See image attached on what happens during an MDT sequence when trying image a ps with msi install.

not working well

**Comment by zeffy** [comment]
Sorry that is happening. Could you post the app crash log files that are referenced in that image, assuming they don't contain any private information? Thanks.

**Comment by smith581** [comment]
Nothing to worry about there
Where are this logs?

Sent from iPhone

On Oct 10, 2017, at 3:35 PM, zeffy <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry that is happening. Could you post the app crash log files that are referenced in that image, assuming they don't contain any private information? Thanks.

**Comment by zeffy** [comment]
Well the image you posted referred to three files:

```
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_...
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_...
C:\Windows\Temp\WER6C0A.wmi.tmp
```

But the first two were cut off, so I don't know the exact location. Those files should give me a better idea what is happening.

**Comment by zeffy** [comment]
Sorry I meant `C:\Windows\Temp\WER6C0A.tmp.wmi.txt`

Typing that out on a phone was tedious, haha.

**Comment by smith581** [comment]
Don’t see that - I am running Windows 7 x64 I was using your latest msi- what switches work??? Error comes up after reboot -

Sent from iPhone

On Oct 10, 2017, at 3:50 PM, zeffy <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry I meant C:\Windows\Temp\WER6C0A.tmp.wmi.txt

Typing that out on a phone was tedious, haha.

**Comment by zeffy** [comment]
Hmm, that's weird. Sorry, I'm not really familiar with GPO deployment at all, and can't really test it on my PC.

Did you follow this link from the readme? http://www.advancedinstaller.com/user-guide/tutorial-gpo.html

**Comment by smith581** [comment]
Mdt deployment basically automated install of windows

Sent from iPhone

On Oct 10, 2017, at 4:00 PM, zeffy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, that's weird. Sorry, I'm not really familiar with GPO deployment at all, and can't really test it on my PC.

Did you follow this link from the readme? http://www.advancedinstaller.com/user-guide/tutorial-gpo.html

**Comment by Sylphide95** [comment]
I'm getting the same errors, here are mine.

[WER692D.tmp.wmi.txt](https://github.com/zeffy/wufuc/files/1373827/WER692D.tmp.wmi.txt)
[WER6363.tmp.appcompat.txt](https://github.com/zeffy/wufuc/files/1373828/WER6363.tmp.appcompat.txt)

**Comment by swshan** [comment]
I try the lastest version meet this error too.

**Comment by zeffy** [comment]
Since this is happening to so many of you, I'm going to see if I can set up a test VM to emulate what is going on. I'll check back when I know more or if I need more information. Thanks for reporting this guys.

Also just to be clear, this is happening to all of you during MDT deployment?

**Comment by smith581** [comment]
For myself - yes

Sent from iPhone

On Oct 10, 2017, at 11:04 PM, zeffy <notifications@github.com<mailto:notifications@github.com>> wrote:


Since this is happening to so many of you, I'm going to see if I can set up a test VM to emulate what is going on. I'll check back when I know more or if I need more information. Thanks for reporting this guys.

Also just to be clear, this is happening to all of you during MDT deployment?
