### ISSUE TITLE
AppX (AppXSVC)

### ISSUE THREAD

**Issue by 2vic** [zeffy/wufuc#111]
Hello. When start a new version of the Wufus in the event log are errors - time exceeded (30000 ms) while waiting for the service connection "Service Shop Windows (WSService)", failed to start the service deployment AppX (AppXSVC)" because of an error in the 
Service had not replied to the request in a timely manner.

**Comment by zeffy** [comment]
Is this on Windows 8.1? 32-bit or 64-bit?

Also is it just this service crashing? Does windows update still work?

Thanks

**Comment by 2vic** [comment]
Re: [zeffy/wufuc] AppX (AppXSVC) (#111)


Здравствуйте, zeffy.

Вы писали 11 октября 2017 г., 11:15:02:





Is this on Windows 8.1? 32-bit or 64-bit?
Also is it just this service crashing? Does windows update still work?
Thanks
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Windows 8.1 64 bit. Windows update works

С наилучшими пожеланиями,
 Victormail                          mailto:2vic@inbox.ru

**Comment by zeffy** [comment]
Okay, thank you. 

I will try to see if I can reproduce this on one of my test VMs. Will comment again when I know more or if I need more information.

**Comment by 2vic** [comment]
Re: [zeffy/wufuc] AppX (AppXSVC) (#111)


Здравствуйте, zeffy.

Вы писали 11 октября 2017 г., 15:56:13:





Okay, thank you.
I will try to see if I can reproduce this on one of my test VMs. Will comment again when I know more or if I need more information.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




I have disconnected in the register of service Appx and WSService (start=4) that there were no mistakes. 
Sorry for bother you.
-- 
С наилучшими пожеланиями,
 Victormail                          mailto:2vic@inbox.ru

**Comment by zeffy** [comment]
Actually, I was able to reproduce this just now. I set up a clean Windows 8.1 VM and updated it, installed wufuc, got this exact error in the event log and a few minutes later several of other services crashed too, and I eventually got a BSOD.

For now I recommend you uninstall wufuc immediately. If the uninstaller is not working, follow [these instructions](https://github.com/zeffy/wufuc#what-to-do-if-you-get-stuck-on-a-black-screen-with-just-a-cursor-after-the-windows-boot-animation) to remove it manually.

**Comment by Whoopwhooppullup** [comment]
Is this limited to wufuc version 0.8.0.143, or does it also affect older versions?

**Comment by zeffy** [comment]
Yes, this issue is limited to 0.8.0.143. **0.7.1.81** should still be fine to use on Windows 8.1. Very sorry for the inconvenience, I'm trying to resolve this as quickly as possible.

**Comment by 2vic** [comment]
Re: [zeffy/wufuc] AppX (AppXSVC) (#111)


Здравствуйте, zeffy.

Вы писали 17 октября 2017 г., 1:48:05:





Yes, this issue is limited to 0.8.0.143. 0.7.1.81 should still be fine to use on Windows 8.1. Very sorry for the inconvenience, I'm trying to resolve this as quickly as possible.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




Hi. wufuc v0.8.0.143 works without bugs, if you disable AppXSVC and WSService (I don't want them). In addition, I disabled the service "Server & computer browser". Otherwise twitch desktop shortcuts when Windows start.
-- 
С наилучшими пожеланиями,
 Victormail                          mailto:2vic@inbox.ru
