### ISSUE TITLE
No new updates

### ISSUE THREAD

**Issue by blue-marine** [zeffy/wufuc#112]
Hi,
this is an awesome program and thank you for making it!
However, I'm encountering one problem. I'm a complete beginner, I installed wufuc_setup_x64.msi for my Win8.1 x64 (as far as I understand, that is all it takes? or do I have to do something with wufuc_v0.8.0.143.zip too?). PC restarted without issues, no warning waiting at the desktop, but when I try checking for updates in Windows Update, nothing happens. As in, the system just keeps checking for updates, for over 20 minutes now, not stopping.

Thanks!

**Comment by zeffy** [comment]
Yeah, the MSI is all you need, the zip is just an alternative installer.

If you can click "check for updates" without getting the unsupported hardware pop up, that means wufuc is working. It's most likely something else causing your problem, you may want to investigate the end of `C:\Windows\WindowsUpdate.log` for clues.

**Comment by Whoopwhooppullup** [comment]
Is this the first time you've run Windows Update on this PC?  If so, the long wait time is normal - subsequent update searches should be much quicker.

**Comment by blue-marine** [comment]
I tried with checking WindowsUpdate.log and some of Microsofts solutions, but nothing's helped, and now I'm also having the recently mentioned "unable to uninstall" issue too. My OS was basically new with barely any software (Mozilla, Discord). I've also become unable to load system restore options to go back to the state before wufuc.
Since I'm a pretty much beginner with computers, I'll probably simply (and sadly) update to Win10.

@Whoopwhooppullup 
Thanks for the suggestion, I'm aware Win Updates might take longer sometimes, and that was not the issue here, since sometimes Win Updater would just end with a red window saying it couldn't get to new updates. I tried fixing that specific error number with Microsoft's solutions but it didn't help, and I don't dare messing further with system files or BIOS.

**Comment by zeffy** [comment]
Agh, I'm really sorry! I had no idea this new release would cause so many problems. I'm probably going to pull it for now to prevent any more of this from happening to people.

Before you update to Windows 10, try manually disabling wufuc following the instructions here, it should fix the unable to uninstall issue you are having:
https://github.com/zeffy/wufuc#what-to-do-if-you-get-stuck-on-a-black-screen-with-just-a-cursor-after-the-windows-boot-animation

**Comment by rautamiekka** [comment]
Yeah, you may (it's very likely) you'll have to wait for hours, but as a rule of thumb, don't wait for longer than 3 hours, just reboot the computer and retry.

Unpatched system checkups will take a long time in the order of minutes (not just 5), but gets faster, but assuming your system has no problems on its end connecting to M$ for updates and the problem is elsewhere you just have to keep retrying, not leaving Windows Update running alone cuz it won't retry forever.

**Comment by blue-marine** [comment]
@zeffy Thanks for your support and putting this much effort! Hope you manage to discover what's causing those issues. I've sadly submitted to W10 because I don't have the time to work around Microsoft's insistent warnings. Sorry I can't provide more info about reproducing these issues.

@rautamiekka I'm aware Win Updates might take longer sometimes (had to wait about an hour once to get it to just start downloading updates), but thanks for the advice on waiting for the reboot.
