### ISSUE TITLE
Stuck on loading screen, SLOW performance when able to get past it

### ISSUE THREAD

**Issue by WackyWombat77** [zeffy/wufuc#114]
I was able to use this for a while with no problems, but started having issues.  When I get stuck in the loading screen I boot into safe mode and delete the svchost.exe as per instructions, then uninstall and reinstall wufuc.exe. But rebooting after reinstalling wufuc.exe causes my system to run SLOW... super slow. I also tried downloading a Windows update as there were 2 new ones for me this morning, but it wouldn't install and would get stuck at "creating a restore point". It tried to install them anyway when I rebooted but just froze (yeah, had to power off the computer with the screen "do not power off up" LOL)

I also started getting a message of "Windows could not connect to the Group Policy Client Service" in the bottom right corner of my screen, seems to only happen when I try having wufuc enabled now.

Without wufuc (or after I delete svchost subkey) system runs fine.  Of course I get those silly "hardware not supported messages" though.

I'm on Windows 7 64 bit, wuaueng.dll version 7.6.7601.23806, using latest stable version of wufuc, sorry couldn't find any logs.

I can reproduce this pretty reliably now, if you need anymore information from me let me know.

Thank you for working on this! Really appreciate the program :-)

**Comment by zeffy** [comment]
I can more or less reproduce this on Windows 8.1. Weirdly though, I had wufuc running on my own W7 machine for over a week and never experienced any kind of slowdowns.

For now I recommend you remove wufuc using the safe mode method and go back to version 0.7.1 until I can come up with a better solution. 

Thanks for reporting this, and I'm very sorry it caused you such inconvenience.

**Comment by WackyWombat77** [comment]
Thanks for the reply :-) Actually, I am using v0.7.1.81, sorry about the confusion. When I clicked on the latest stable version link on main page that's the one it took me to.

**Comment by zeffy** [comment]
Are you positive that you were using 0.7.1.81 when you encountered this?

I had released 0.8.0.143 a little over a week ago but decided to pull it yesterday because many people were experiencing issues similar to what you describe. So if you downloaded wufuc any time in the last week, then you most likely had 0.8.0.143, not 0.7.1.81.

**Comment by WackyWombat77** [comment]
I'm not sure now (why I deleted previous message), actually just noticed that, about to uninstall what I have now and install .7.1.81

**Comment by WackyWombat77** [comment]
I was having the problems with version .8, very sorry about the confusion.

I uninstalled it and went to version .7.1 and things are great now, rebooted several times, no slow-down at all, and even managed to install a Windows update!  Thank you for the help :-)

**Comment by zeffy** [comment]
No need to apologize, it's really my own fault for all the confusion. :) I'm glad 0.7.1 is working for you, though. Hopefully I can figure out what is causing all the problems in 0.8 soon and get a new version out that isn't completely busted...
