### ISSUE TITLE
Patch is not working.

### ISSUE THREAD

**Issue by LordSnax** [zeffy/wufuc#119]
Howdy All,

I am having an issue with the Zeffy Patch, I have two computers running Windows 7 on the new Ryzen processors. The first one, which is mine, is a Ryzen 5 and the other computer, which is my friend's computer, has a Ryzen 7.

My computer is not showing the "Unsupported Hardware" message, but my Friend's computer is. I have tried different versions of the patch, but to no avail.

Any Help is greatly appreciated,
Lord Snax

**Comment by zeffy** [comment]
Hi, apologies for taking so long to get back to you.

Can you open an elevated command prompt window (open your start menu, type `cmd`, right click it and select Run as Administrator) paste the following commands into it, and then copy the text that opens in notepad into this issue:

```
REG QUERY HKLM\SYSTEM\CurrentControlSet\services\wuauserv >"%temp%\wufuc_tmp.log"
REG QUERY HKLM\SYSTEM\CurrentControlSet\services\wuauserv\Parameters >>"%temp%\wufuc_tmp.log"
schtasks /Query /TN "wufuc.{72EEE38B-9997-42BD-85D3-2DD96DA17307}" /V /FO List >>"%temp%\wufuc_tmp.log"
notepad "%temp%\wufuc_tmp.log"
echo.
```

That should give me a general idea what's going on.

Thanks.

**Comment by LordSnax** [comment]
Thanks for the reply zeffy, but my friend decided to just upgrade his PC to Windows 10. Its a bummer.
My PC is still running Windows 7 and is running fine.
Hope all is well,
Lord Snax

**Comment by zeffy** [comment]
Ah, that's a shame. I'm happy wufuc is working well on your PC, though!
