### ISSUE TITLE
Batch installer doesn't warn the user when they clone the repository instead of downloading a release

### ISSUE THREAD

**Issue by PaperCuTTzi** [zeffy/wufuc#121]
Hey,

nothing really changed when I ran the batch as an administrator. The command prompt popped up and closed itself, so the batch ran, but it had no effect.

I read your troubleshoot with this ticket [https://github.com/zeffy/wufuc/issues/116](url) and extracted the info by myself in advance.

> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\wuauserv
>     PreshutdownTimeout    REG_DWORD    0x36ee800
>     DisplayName    REG_SZ    @%systemroot%\system32\wuaueng.dll,-105
>     ImagePath    REG_EXPAND_SZ    %systemroot%\system32\svchost.exe -k netsvcs
>     Description    REG_SZ    @%systemroot%\system32\wuaueng.dll,-106
>     ObjectName    REG_SZ    LocalSystem
>     ErrorControl    REG_DWORD    0x1
>     Start    REG_DWORD    0x2
>     DelayedAutoStart    REG_DWORD    0x1
>     Type    REG_DWORD    0x20
>     DependOnService    REG_MULTI_SZ    rpcss
>     ServiceSidType    REG_DWORD    0x1
>     RequiredPrivileges    REG_MULTI_SZ    SeAuditPrivilege\0SeCreateGlobalPrivilege\0SeCreatePageFilePrivilege\0SeTcbPrivilege\0SeAssignPrimaryTokenPrivilege\0SeImpersonatePrivilege\0SeIncreaseQuotaPrivilege\0SeShutdownPrivilege
>     FailureActions    REG_BINARY    80510100000000000000000003000000140000000100000060EA000000000000000000000000000000000000
> 
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\wuauserv\Parameters
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\wuauserv\Security
> 
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\wuauserv\Parameters
>     ServiceDll    REG_EXPAND_SZ    %systemroot%\system32\wuaueng.dll
>     ServiceMain    REG_SZ    WUServiceMain
>     ServiceDllUnloadOnStop    REG_DWORD    0x1

Thanks a lot in advance.

**Comment by zeffy** [comment]
Hi, sorry for the delay!

Which package are you trying to install, `wufuc_v0.7.1.81.zip`? 

If you haven't already, perhaps try your luck with the MSI installer instead: https://github.com/zeffy/wufuc/releases/download/v0.7.1.81/wufuc_setup_x64.msi

**Comment by PaperCuTTzi** [comment]
The .msi installer worked like a charm. Thank you very much^^
I was using the batch from the latest version, which I downloaded directly from this repository, before.

**Comment by zeffy** [comment]
That's probably why, if you just clone the repository then you have to compile the DLLs and such first, otherwise it won't work. I should probably look into why the batch script was just closing though, that shouldn't happen regardless.

Thanks for reporting this, and I hope wufuc is working to your liking. :)
Please let me know if you have any other questions or issues.

Going to leave this issue open to remind me to look at the batch script installer.

**Comment by zeffy** [comment]
Just checked this and the batch installer seems to no longer have this problem, so I'm going to close this.
