### ISSUE TITLE
Black Screen no svchost.exe subkey 0.7.1.81

### ISSUE THREAD

**Issue by Schmidlapp84** [zeffy/wufuc#122]
Hi Zeffy, I also have the same issue with the black screen/cursor at login on 0.7.1.81.  I also do not have the svchost.exe subkey to delete as you suggested. 

The black screen goes away after minute then I can use the computer as normal.  The patch did resolve the "unsupported hardware" message but the black screen makes boot times to desktop rather long.

If its worth noting, my PC had Win 7 Ultimate freshly installed last night which appears to have resolved a recurring BSOD I was getting in Win 10 Pro IRQL_NOT_LESS_OR_EQUAL.  I also noticed when searching Google that I did not have the windows updates KB4012218 or KB4012219 installed on my computer.  I'm unsure why. 

Any help with the black screen would be appreciated when you got it worked out but thanks in the mean time!

**Comment by Schmidlapp84** [comment]
I have uninstalled 0.7.1.18 but am still getting the black screen.

**Comment by Schmidlapp84** [comment]
![img_0046](https://user-images.githubusercontent.com/33776234/32980090-1a6c6958-ccac-11e7-9276-f0a3e1c42655.JPG)

**Comment by Schmidlapp84** [comment]
I found that my black screen issue was caused by my Killer NIC software. I've since removed it and installed just the driver and its working properly now. Thanks

**Comment by zeffy** [comment]
I'm glad you were able to solve your issue! 

Please let me know if you have any other questions or problems.
