### ISSUE TITLE
Detected that no supported updates are installed

### ISSUE THREAD

**Issue by umeo** [zeffy/wufuc#123]
--The error log is as below:

<details>

## Operating System

```
BuildNumber=7601

Caption=Microsoft Windows 7 专业版 

MUILanguages={"zh-CN"}

OSArchitecture=64-bit

OSLanguage=2052

Version=6.1.7601

```

## Processor

```
Description=Intel64 Family 6 Model 158 Stepping 9

Family=11

Manufacturer=GenuineIntel

Name=Intel(R) Pentium(R) CPU G4560 @ 3.50GHz

NumberOfCores=2

NumberOfLogicalProcessors=4

ProcessorId=BFEBFBFF000906E9

Revision=

```

## Installed Hotfixes

```
HotFixID=KB2479943

InstalledOn=5/3/2017

HotFixID=KB2491683

InstalledOn=5/3/2017

HotFixID=KB2506212

InstalledOn=5/4/2017

HotFixID=KB2534111

InstalledOn=4/29/2017

HotFixID=KB2621440

InstalledOn=5/4/2017

HotFixID=KB2685811

InstalledOn=4/29/2017

HotFixID=KB2706045

InstalledOn=5/4/2017

HotFixID=KB2718704

InstalledOn=5/4/2017

HotFixID=KB2736422

InstalledOn=5/7/2017

HotFixID=KB2789645

InstalledOn=5/7/2017

HotFixID=KB2999226

InstalledOn=5/24/2017

HotFixID=KB3109560

InstalledOn=5/13/2017

HotFixID=KB3177467

InstalledOn=5/25/2017

HotFixID=KB3178034

InstalledOn=5/13/2017

HotFixID=KB3185911

InstalledOn=5/13/2017

HotFixID=KB3205394

InstalledOn=5/13/2017

HotFixID=KB4012212

InstalledOn=5/17/2017

HotFixID=KB4014579

InstalledOn=5/12/2017

HotFixID=KB4019263

InstalledOn=5/12/2017

HotFixID=KB4022722

InstalledOn=6/19/2017

HotFixID=KB976902

InstalledOn=11/21/2010

```

## wuaueng.dll Properties

```
MD5 哈希(文件 C:\windows\System32\wuaueng.dll):
88 00 9d b9 e1 16 6b 6b 67 13 a8 58 c1 76 fe cd

SHA1 哈希(文件 C:\windows\System32\wuaueng.dll):
f2 4e 24 fe ff ef e8 40 b5 d7 ed 20 eb c9 9f b5 32 83 1c 30

SHA256 哈希(文件 C:\windows\System32\wuaueng.dll):
cb f4 c6 3d 3c 5d 14 af 3c 3f 0d 9c 48 e5 ac 9e 7a 43 23 bf b0 36 3e 99 48 fd 80 19 63 be 14 67

CreationDate=20170618223402.223204+480

FileSize=2651136

InstallDate=20170618223402.223204+480

LastAccessed=20170618223402.223204+480

LastModified=20170510231453.978724+480

Version=7.6.7601.23806

```
</details>
-------------------------------------
and the output message when run by the bat file are as below:
----------------------------
aio-wuaueng.dll-patch.bat
Copyright (C) 2017 zeffy <https://github.com/zeffy>
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see COPYING.txt for details.

Checking system requirements...

Detected supported operating system: Windows 7 x64

Detected that no supported updates are installed! If you are getting
unsupported hardware errors in Windows Update, please create an issue
and I will try to help you out.

https://github.com/zeffy/kb4012218-19/issues

Gathering debugging information, please wait...

Done! Please copy the text from Notepad into your GitHub issue.
Opening log file in 5 seconds...

Press any key to exit...

**Comment by zeffy** [comment]
Hey there, it looks like you're using an older version (<0.6) of wufuc, please download the [**latest version**](https://github.com/zeffy/wufuc/releases/latest) (wufuc_setup_x64.msi) and try it out. It should solve any problems you are having. You may have to restart to fully remove the old patch after you install the new one.

For more information about how the new patch works, see the [README](https://github.com/zeffy/wufuc#how-it-works).

I'm going to close this issue for now, but if you have any more questions or issues please feel free to reopen it.
