### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by San-James** [zeffy/wufuc#124]
My antivirus accuses IPD.ALEXA.51 virus in the wufuc.dll file when installing.
Path C:\Program Files\wufuc\wufuc.dll
...with the wufuc_setup_x86.msi Installer

**Comment by zeffy** [comment]
There is no virus. wufuc has to inject itself into a svchost.exe process in order to patch Windows Update, which may be considered by some antiviruses to be characteristic of malware. Just restore wufuc.dll from quarantine and add it to the exception list in your antivirus program.
