### ISSUE TITLE
Didn't work - Unsupported Hardware pop up on Ivy Bridge i74930k

### ISSUE THREAD

**Issue by 26kick** [zeffy/wufuc#126]
Hi, I'm just putting a system together and am using Win7 for the 1st time.  I got the Unsupported Hardware pop up with my i74930k.  I installed the latest stable build from this site this morning and tried to update Windows and it didn't work.  I've searched around and haven't seen this issue associated with this processor.  Please advise.  Thank you.

**Comment by zeffy** [comment]
What exactly isn't working? 

Is there any specific error code Windows Update is showing you when you try to update, or are you still getting the Unsupported Hardware pop up?

**Comment by 26kick** [comment]
Hi, thanks for the quick response!  I'm about to head to a dr appt but I got the pop up and WU error 80070103. I look forward to your suggestion, thank you.

**Comment by 26kick** [comment]
Any help on this would be much appreciated.
![img_20171211_075007](https://user-images.githubusercontent.com/34450379/33889671-b40aac94-df05-11e7-8286-624202f86774.jpg)

**Comment by zeffy** [comment]
Hey @26kick, very sorry for the delay; I've been without a usable computer for several days.

It's hard to tell without wufuc's log files (`wufuc.rundll32.exe.log` and `wufuc.svchost.exe.log`), but this is **probably** caused because your Windows Update service is configured in a weird way. Can you run `sc queryex wuauserv` in a command prompt window and copy the output here? And upload the log files from wufuc's folder that I mentioned previously if they are present.

**Comment by 26kick** [comment]
Hi Zeffy, I've had no time to work on this issue.  Thank you so much for your response.  I will get those log files for you when I can.  I'm not quite sure how to get them, to be honest, but I'll figure it out.  

I did find that there was one update that was failing every time from NVIDIA so I hid it.  I did still get the unsupported pop up at that time though.  Thanks again and I'll get back with you.

**Comment by zeffy** [comment]
@26kick The log files will be in the same folder where you installed wufuc to.

**Comment by 26kick** [comment]
Thank you, Zeffy. I have been getting by. It's interesting, updates work but I still get the pop-up. I look forward to trying the new version! Thanks so much for following up.

**Comment by zeffy** [comment]
The new version is up as of a few minutes ago, feel free to try it out when you get a chance! :)

https://github.com/zeffy/wufuc/releases/latest
