### ISSUE TITLE
WUAUENG.DLL

### ISSUE THREAD

**Issue by SoapDisoriented** [zeffy/wufuc#127]
hi when trying to install i get this error : "file wuaueng.dll is under the minimum supported version."
what is that .DLL file and how do i fix it?

~Thanks

**Comment by zeffy** [comment]
@SoapDisoriented This error shows when you don't have updates installed to the point where you are getting the "unsupported hardware" message. To fix the error, just keep installing Windows Updates until it gives you the unsupported hardware pop up message, and then you can install wufuc (if you need it).

**Comment by SoapDisoriented** [comment]
great thanks!
