### ISSUE TITLE
Detected that wuaueng.dll is below the minimum supported version

### ISSUE THREAD

**Issue by canislupus85** [zeffy/wufuc#129]
I received the following error when trying to install the fix:

![capture](https://user-images.githubusercontent.com/34718714/34218642-ba3bffaa-e57c-11e7-8026-668b0fb5725b.PNG)

I went to microsoft's site and downloaded the update package which brought the version to:  7.6.7601.23453

I am running Windows 7 SP1 x64.  Any help would be appreciated.

**Comment by chris299** [comment]
I experienced the same problem. however, with that version the "normal" Windows-Update still worked and brought me to a version where wufuc was needed....

**Comment by zeffy** [comment]
Hi, sorry for the delay. What @chris299 says is correct, just keep updating with Windows Update normally until you start getting the Unsupported hardware popup, then you can install wufuc.

This error message will be removed in the next version of wufuc, so you can install it regardless of the wuaueng.dll version (no ETA yet but it's coming along well, I just have to implement a few features and do extensive testing...).

**Comment by zeffy** [comment]
New update coming very soon that will fix this.
