### ISSUE TITLE
Unsupported Hardware

### ISSUE THREAD

**Issue by aruncannes** [zeffy/wufuc#133]
Windows update is not working in windows 7 os (dell inspiron 15 5000 series 7 th gen)

**Comment by UnbreakCode** [comment]
Whats the error code?

**Comment by aruncannes** [comment]
Code 80240037

**Comment by aruncannes** [comment]
It is very urgent please give any solution for that immediately

**Comment by UnbreakCode** [comment]
Check if youre using x86 or x64 and use the latest version,reinstall it and restart

**Comment by aruncannes** [comment]
Iam using x64.how i reinstall the os i dont have original give some instruction how to do the process

**Comment by UnbreakCode** [comment]
https://github.com/zeffy/wufuc/releases/latest download and click on remove

**Comment by aruncannes** [comment]
I done it now what i do my friend

**Comment by UnbreakCode** [comment]
try reinstall

**Comment by aruncannes** [comment]
I installed it

**Comment by UnbreakCode** [comment]
and reboot

**Comment by aruncannes** [comment]
Now i have to restart my computer and check the updates?????

**Comment by UnbreakCode** [comment]
yes

**Comment by aruncannes** [comment]
I think it is working thank u very much my friend

**Comment by UnbreakCode** [comment]
no problem so i think it's solved ;-)
