### ISSUE TITLE
¿Is danger use Win7 / 8.1 with seventh?

### ISSUE THREAD

**Issue by Borjahen** [zeffy/wufuc#134]
Sorry for my bad english.

If I install the motherboard drivers can use Win 7 / 8.1 without install Wufuc without problems in i3-seventh?

Is danger? for example for the hardware or the system?

**Comment by UnbreakCode** [comment]
You still can use it without problems.It shouldn't be danger

**Comment by zeffy** [comment]
Like @UnbreakCode says, you should be able to install the drivers with no problems.
