### ISSUE TITLE
One time only...

### ISSUE THREAD

**Issue by nartaki** [zeffy/wufuc#135]
I installed after the first notification appeared and it worked.2 days later i get the msg again...

**Comment by zeffy** [comment]
Sorry that's happening, sometimes the patch can be a little finicky. You can try uninstalling and reinstalling wufuc and see if that works.

I'm currently working on a new version that should take care of this behavior, but still no ETA on it...

**Comment by nartaki** [comment]
It has a weird way of working on Fx-6300 (You should add to affected CPU's btw) .Some updates come in and then fail,others come in and install,still getting a years or so "updates"! So working as intended for now.

**Comment by zeffy** [comment]
Sorry for the delay in my response. 

I'll add Fx-6300 to the list of affected CPU's thank you for letting me know about it!
