### ISSUE TITLE
KB3150513

### ISSUE THREAD

**Issue by sshmanko** [zeffy/wufuc#138]
First of all big thanks for making this project, it is a lifesaver!

On Windows 8.1 (6.3.9600) installation of wufuc did not disable popup window, which appeared on every reboot. However updates started working as expected.

Almost all articles mention some KB401xxx updates, however I had none of these installed.
Finally in reddit I have found mentions of KB3150513 which caused popups in my case.

**Comment by zeffy** [comment]
Sorry for the delay in my response.

There is a new version coming out very soon that should fix this.
