### ISSUE TITLE
Patch cpu restriction mixed reality

### ISSUE THREAD

**Issue by eychei** [zeffy/wufuc#139]
Hi,

i dont know how to contact anyone so i am opening an issue. I am very sorry for that. 
I am trying to patch the windows mixed reality app to remove the CPU restriction. 
This restricts the headset to 60hrz on 2 core systems. Minimum requirement is 4 cores for ultra mode. 

I am using ida 7 and do have some knowledge in reverse engineering. Found the cpuid calls and the part where it asks for logicalcores/physicalcores. 
I'm stuck and would need some help. 

I do not want to hijack this github page. Please can i have an email address to contact someone of this group. 

Thx
Eychei

**Comment by zeffy** [comment]
Sorry for the delay in my response.

If you want to contact me to ask general reverse engineering questions regarding this, I may be able to help. Feel free to drop by my Discord server and message me there. https://discord.gg/G8PD2Wa
