### ISSUE TITLE
Apparent License Violation (GPL versus MSR-SSLA)

### ISSUE THREAD

**Issue by NoMoreFood** [zeffy/wufuc#140]
This appears to be a derivative work of Detours.   Doesn't the use of Microsoft Research Shared Source License Agreement (MSR-SSLA) conflict with GPL?  

At the very least, I believe the following restriction conflicts with GPL: "That if you distribute the Software or any derivative works of the Software, you will distribute them under the same terms and conditions as in this license, and you will not grant other rights to the Software or derivative works that are different from those provided by this MSR-SSLA."

**Comment by zeffy** [comment]
Hmm, you appear to be correct. The stuff with detours there is just in-progress code, nothing that has been in a release build. 

I was planning on switching to a different hooking lib with a GPL-compliant license before the next release, though, so that should clear this up, yes?

**Comment by NoMoreFood** [comment]
Correct.  Or, in theory, you could release this project itself under MSR-SSLA and remove the GPL tag.

**Comment by zeffy** [comment]
This has been resolved. wufuc has been ported over to use [minhook](https://github.com/TsudaKageyu/minhook), and everything related to Detours was scrubbed from the git history. 

Closed.

**Comment by NoMoreFood** [comment]
@zeffy Just an FYI --- apparently Microsoft just released Detours under MIT.  

https://github.com/microsoft/detours

**Comment by zeffy** [comment]
@NoMoreFood That's awesome! I'll probably just stick with Minhook for now because it seems to be doing its job, but I'll keep my eye on that. Thanks for sharing.

**Comment by zeffy** [comment]
Actually, I changed my mind! After considering this further, minhook has been unmaintained for quite some time, so I think it would be better to switch to Detours now that it has a more open (GPL-compatible) license. Look forward to this in the next release!
