### ISSUE TITLE
IS IT SAFE TO PATCH CPU WHILE ON WUFUC ?

### ISSUE THREAD

**Issue by nic011** [zeffy/wufuc#144]
I'm a bit concerned about how safe it is to update with M$ or Intel security update patches since they are meant for specific cpus and hardware. Maybe it's a noob question i know , but i'm not a coder or engineer to fully understand how wufuc works . Just want to be sure updating is completely safe .
On a win8.1 x64 with kabylake cpu.

**Comment by zeffy** [comment]
There has previously been incompatible updates that should not be installed, yes. See #132 for more information.

As far as I know this has been resolved though, at least according to Microsoft's KB article here: https://support.microsoft.com/en-us/help/4073707/windows-os-security-update-block-for-some-amd-based-devices

Sorry for the delay in my response. I hope this clears up your question.
