### ISSUE TITLE
Installer hangs on 'Preparing files for removal'

### ISSUE THREAD

**Issue by BoffinbraiN** [zeffy/wufuc#150]
OS: Windows 7 Ultimate x64
Running wufuc_v1.0.0.191-x64.msi

When the installer gets to the step 'Preparing files for removal' it gets to about 5% and then makes no progress, even after waiting 10 minutes. Pressing Cancel and Yes won't cancel the installation so the only option is to kill msiexec.exe from the task manager.

No log is available. The installation folder doesn't exist at this point.

**Comment by zeffy** [comment]
The installer is likely hanging while trying to stop wuauserv or something similar, you can try restarting your PC and then use the batch (zip) installer instead, just copy the contents of the zip file to `C:\Program Files\wufuc` before you run `install_wufuc.bat`, and then follow the prompts.

**Comment by BoffinbraiN** [comment]
Unzipped and installed via the batch files. Works like a charm. Thanks! :smile:

**Comment by zeffy** [comment]
Glad to hear it!
