### ISSUE TITLE
Windows Server 2008 R2

### ISSUE THREAD

**Issue by kramytech** [zeffy/wufuc#151]
I am having the same "Unsupported Hardware" issue running Windows Server 2008 R2 with a Xeon E3 v6 processor.  Will these same patches work for this OS?  Thanks

**Comment by zeffy** [comment]
Yes, Server 2008 R2 is supported.

**Comment by kramytech** [comment]
Awesome.  It worked perfectly with Windows Server 2008 R2.  Thanks so much :)

**Comment by zeffy** [comment]
No problem, happy to hear it!
