### ISSUE TITLE
install on win7-32 fails 

### ISSUE THREAD

**Issue by sh-dvl** [zeffy/wufuc#152]
- wufuc v1.0.0.191
- windows7 32bit (Version 6.1 Build 7601 SP1)

installer fails with error-msg, but without clear reason/log
screenshot of msg will be attached.

maybe it would be possible to create a simple batch, which might be better debuggable?

**Comment by sh-dvl** [comment]
![wufuc-failed](https://user-images.githubusercontent.com/26329004/38753516-2add4f68-3f4e-11e8-86fd-cdb3a64e7a40.png)

**Comment by sh-dvl** [comment]
due to german-install, the msg is also in german. sorry.
it says something like: "there's a problem with this installer-packet. a program which is executed during installation failed. contact your support or the manufacturer of the installer-packet"

**Comment by zeffy** [comment]
Probably fixed this in the latest release. I removed the "abort on failure" when stopping and starting `wuauserv`, so even if they time out it should still succeed. https://github.com/zeffy/wufuc/releases/latest
