### ISSUE TITLE
unsupported hardware popups

### ISSUE THREAD

**Issue by chrcoluk** [zeffy/wufuc#155]
Can these be blocked as well?

Basically this mod blocks the Windows Update blacklist, but it doesnt stop the random popups, that appear outside of windows update.

**Comment by UnbreakCode** [comment]
It should block this message too.Maybe try a reinstall.

**Comment by zeffy** [comment]
As stated above, it should be blocking the popup too. Could you post your wufuc.log file please?

**Comment by AQXT1000** [comment]
With me too, already did a reinstall and it keeps popping up

**Comment by piratesephiroth** [comment]
There's a possible solution in #156
