### ISSUE TITLE
Porting Project to Build with VS2012?

### ISSUE THREAD

**Issue by LukeDogwalker** [zeffy/wufuc#157]
Can you provide a Visual Studio Solution that works in Visual Studio 2012 so I can build it?  It looks like your project requires VS 2015.  I would've thought a fellow "true believer" :-) who prefers Windows 7 would be using the oldest VS edition capable of building the software.

I tried to switch it to toolset v110 (VS2012), but when I try to build I get many assertion failures, such as:

Error	1	error C2118: negative subscript	C:\wufuc\inc\phnt\ntexapi.h	3579	1	wufuc
here:
C_ASSERT(sizeof(KUSER_SHARED_DATA) == 0x708);

and
Error	2	error C2061: syntax error : identifier 'PCFG_CALL_TARGET_INFO'	C:\wufuc\inc\phnt\ntmmapi.h	504	1	wufuc
here:
PCFG_CALL_TARGET_INFO CallTargetInfo;

There also don't seem to be any docs on building the project, such as a BUILDING.md, in the repository.  Is that not something you support?

I'm aware that VS2015 has a free version, but that's not the point - I'd rather not have so many VS versions installed on my machine.

**Comment by zeffy** [comment]
>Can you provide a Visual Studio Solution that works in Visual Studio 2012 so I can build it? It looks like your project requires VS 2015. 

To compile wufuc you need the latest version of Visual Studio 2017 and [WDK](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) installed, that's it. I do not plan on supporting other versions of VS, as I don't have the time to spend maintaining separate solutions.

You are however absolutely free to fork wufuc and figure it out yourself; I have no problem with this.

>I would've thought a fellow "true believer" :-) who prefers Windows 7 would be using the oldest VS edition capable of building the software.

Have to disagree with you on this, VS 2017 works perfectly fine on Windows 7 (arguably better than 2012 or even 2010), and has no problem building software targeting either Windows 7 or 8.1.

>There also don't seem to be any docs on building the project, such as a BUILDING.md, in the repository. Is that not something you support?

You have a point here, I will add documentation for building requirements in the near future.
