### ISSUE TITLE
batch file uninstall

### ISSUE THREAD

**Issue by jjurkus** [zeffy/wufuc#159]
I have an issue with the newest version of wufuc, 1.0.1.201. We are using Windows 7 N Professional SP1 64-bit, and we were using 0.7.1.81 previously.

We are using OPSI to deploy packages to all clients, and 12 of the newer computers have a core i3-7100 cpu. That's where wufuc comes in. Made a package of the previous version, all went well.
With the newer version I have a couple of problems, and I think there might be an error in the install/uninstall batch file.

snippet from 0.7.1.1.81 install_wufuc.bat:
```
rundll32 "%wufuc_dll%",Rundll32Unload
```

snippet from 1.0.1.201 install_wufuc.bat:
```
rundll32 "%wufuc_dll_fullpath%",RUNDLL32_Unload
````

Now in the older wufuc dll files the function Rundll32Unload was available, I checked this via dependency walker 2.2
The newer wufuc dll files do not have the RUNDLL32_Unload function. It is called RUNDLL32_UnloadW.

At first my package did not work, because it used the RUNDLL32_Unload function. After changing it to RUNDLL32_UnloadW the script seems to work.

**Comment by jjurkus** [comment]
screenshot of dependency walker for wufuc64.dll (1.0.1.201)
![wufuc-depends](https://user-images.githubusercontent.com/9963052/40743045-b87a82ec-6450-11e8-8922-49ab719b40b4.png)

**Comment by zeffy** [comment]
Not an error, it is meant to be like that. [See the documentation for Rundll](https://support.microsoft.com/en-us/help/164787/info-windows-rundll-and-rundll32-interface); specifically this part:
> ### Special Notes On Differences Between Windows 95 And Windows NT
>On Windows NT, Windows 2000, and Windows XP the behavior of Rundll32.exe is slightly different, in order to accommodate UNICODE command lines.
>
>
>**_Windows NT first attempts to GetProcAddress for &lt;EntryPoint&gt;W_**. If this entry point is found, then the prototype is assumed to be:
>```   void CALLBACK
>   EntryPointW(HWND hwnd, HINSTANCE hinst, LPWSTR lpszCmdLine,
>               int nCmdShow);
>```
>This is the same as the ANSI EntryPoint, except that the lpszCmdLine parameter is now a UNICODE string.

What are the actual problems you are experiencing that lead you to believe something was wrong?

**Comment by jjurkus** [comment]
Right, I'll change that back then. I got a lot of errors from rundll32 about the entry point that was not found.

I was thinking I fixed things because after a change everything went well. But the fix was only tested with the newer wufuc installation, and not with the older.

```
[5] [mei 30 21:22:58:437] [win7-wufuc]     Execution of: Files_uninstall_64 /64Bit
[5] [mei 30 21:22:58:437] [win7-wufuc]     
[6] [mei 30 21:22:58:437] [win7-wufuc]         Search "C:\Program Files\wufuc\"
[6] [mei 30 21:22:58:437] [win7-wufuc]         Search "C:\Program Files\wufuc\*.*"
[6] [mei 30 21:22:58:438] [win7-wufuc]         File "C:\Program Files\wufuc\wufuc.xml"
[6] [mei 30 21:22:58:438] [win7-wufuc]           The file has been deleted
[6] [mei 30 21:22:58:438] [win7-wufuc]         File "C:\Program Files\wufuc\wufuc64.dll"
[4] [mei 30 21:22:58:438] [win7-wufuc]           Warning: The file could not be deleted
[6] [mei 30 21:22:58:438] [win7-wufuc]         File "C:\Program Files\wufuc\wufuc64.rundll32.exe.log"
[6] [mei 30 21:22:58:438] [win7-wufuc]           The file has been deleted
[6] [mei 30 21:22:58:438] [win7-wufuc]         File "C:\Program Files\wufuc\wufuc64.svchost.exe.log"
[6] [mei 30 21:22:58:438] [win7-wufuc]           Target file was in use, move / rename should be completed after reboot.
[4] [mei 30 21:22:58:438] [win7-wufuc]         Warning: "Directory C:\Program Files\wufuc" cannot be deleted, error 145 ("The directory is not empty.<")
```

So I was not unloading the old version properly, the dll was still in use. Somehow the old dll was used for the new installation command, because RUNDLL32_Unload (or RUNDLL32_UnloadW) couldn't be found. OPSI rebooted the computer after that.

Changed that reboot behaviour and some other things. Now working. Yep, no error in wufuc. Thanks for the support and your work on wufuc.

**Comment by zeffy** [comment]
@jjurkus No problem, most likely what happened

**Comment by zeffy** [comment]
@jjurkus No problem, I'm glad you were able to fix it. In the next version I will add compatible export aliases for the old function names, so this shouldn't be an issue anymore.

By the way, in the current version of the batch scripts you can invoke  the installer/uninstaller with `/UNATTENDED /NORESTART` for a non-interactive install that you can integrate into your own script.

Also another thing, I'm don't believe it had anything to do with this, but just for information: you must run the rundll32 Unload command as an administrator or wufuc won't respect it (this was an intentional design decision to prevent non-privileged users from potentially turning it off and causing headaches for sysadmins).

(PS, Sorry if you got several notifications for this comment, I had to repost this a couple times because I kept accidentally leaving out information.)

**Comment by jjurkus** [comment]
OPSI runs as a system account, so no problems there. Check it out (opsi.org) if you need to deploy operating systems and/or software. It's free open-source. I can also support all my home users (family, friends, myself) with it. It has its quirks, but there's no voodoo involved to make things work.

I really appreciate your effort, but don't waste any time for me. I'm used to changes in software, and did change the script when the new version was out. I messed up somewhere else.
