### ISSUE TITLE
message still appears

### ISSUE THREAD

**Issue by vsrawat** [zeffy/wufuc#163]
I have installed wufuc v1.0.1.201 on w8-64 bit
I am able to install windows updates, that was not possible before installing your patch.
but THE message still appears.

[wufuc.1.log](https://github.com/zeffy/wufuc/files/2204621/wufuc.1.log)

I have installed your patch several times whenever I see that message, but message continues appearing.

Thanks.
-- 
Rawat

**Comment by Shinji200** [comment]
I think this is the same as the Issue #158 that I opened, if you only get the message at the start of windows logon then it's kind of expected, as soon as you can download updates I don't think you have something to worry about.

Regards!

**Comment by vsrawat** [comment]
I agree.

Major problem was not being able to check-download updates, that is solved by your lovely software.

Now only that huge message appears on every boot, I close that, so no problem, it is just irritating.

Though, that message sort of tells that something related to the basic problem is still active.

Thanks.
