### ISSUE TITLE
Unsupported Hardware message after installing KB4019264 or KB4019215 even after applying patch

### ISSUE THREAD

**Issue by zeffy** [zeffy/wufuc#20]
These updates appear to have just come out (they are marked as 5/5/2017?). I'm assuming they will still include the CPU blocking.

I will keep this issue updated with findings and close it once the new xdeltas are made.

Update: It seems like the wuaueng.dll in these updates is exactly the same as the one in the last three updates, at least in Windows 7. Checking Windows 8.1 now.

Update 2: Windows 8.1 wuaueng.dll is identical to the previous updates as well. Pushing new release shortly.

**Comment by zeffy** [comment]
New release adds support for these updates: https://github.com/zeffy/kb4012218-19/releases

**Comment by zeffy** [comment]
Many people have been reporting issues since these updates were released, so I'm reopening this until I figure it out. #22 #23 #24

**Comment by zeffy** [comment]
Update on this: I've tried replicating this problem on my own setup, but the patch is still working for me with KB4019264; I can check for updates without any errors. 

I'm not really sure where to proceed at this point. If anyone else is having this problem I would really appreciate more information that could help me determine the issue.

**Comment by zeffy** [comment]
@korolartemnexus @Moltresrider @naldiegn Could you try running 
```bat
sfc /SCANNOW

**Comment by naldiegn** [comment]
I did that, still get the pop upOn May 13, 2017 12:06 AM, zeffy <notifications@github.com> wrote:@korolartemnexus @Moltresrider @naldiegn Could you try running
sfc /SCANNOW

**Comment by zeffy** [comment]
Could you try again with the newest version I just released?
Run `sfc /SCANNOW` again first, reboot, then run the new v0.5rc2 patch script.

If that doesn't work, I really don't know. I can't reproduce this issue no matter what I do on my VM.

**Comment by naldiegn** [comment]
Will do later today when I get home On May 16, 2017 10:22 PM, zeffy <notifications@github.com> wrote:Could you try again with the newest version I just released?
Run sfc /SCANNOW again first, reboot, then run the new v0.5rc2 patch script.
If that doesn't work, I really don't know. I can't reproduce this issue no matter what I do on my VM.

**Comment by KZ3D** [comment]
I ran the new v0.5rc2 patch script on my Win7 64 bit system (7th gen. i5 CPU) and it worked fine again (Windows update).

**Comment by KZ3D** [comment]
I ran the wufuc v0.6.1 patch script on my Win7 64 bit system (7th gen. i5 CPU) and it worked fine again (after the last patch tuesday).

**Comment by zeffy** [comment]
@KZ3D Awesome! Glad its working again for you.

**Comment by KZ3D** [comment]
I ran the wufuc v0.7.0.35 patch script on my Win7 64 bit system (7th gen. i5 CPU) and it worked fine (after installing the KB4022168). Thank you for your hard work again.

**Comment by vroy0001** [comment]
I was redirected here from the M560 patch thing BTW, so I'm not sure this is the right place, but I can verify I was able to install 8.1 (Industry Embedded Pro, if it matters) in a VM on my M560 box.

**Comment by Donaldme** [comment]
Hi! The patch wufuc_v1.0.1.201-x64/wufuc_v1.0.1.201-a52637d4 isn't working for my system: win81pro64 and Ryzen1800. Patch wufuc_v0.7.1.81 on the other hand works well.
Just my 2 cents. Thank you!
