### ISSUE TITLE
Still getting unssuported hardware error

### ISSUE THREAD

**Issue by jannos52** [zeffy/wufuc#28]
InstalledOn=5/15/2017

HotFixID=KB3138910

InstalledOn=5/15/2017

HotFixID=KB3139398

InstalledOn=5/15/2017

HotFixID=KB3139914

InstalledOn=5/15/2017

HotFixID=KB3140245

InstalledOn=5/15/2017

HotFixID=KB3147071

InstalledOn=5/15/2017

HotFixID=KB3150220

InstalledOn=5/15/2017

HotFixID=KB3150513

InstalledOn=5/15/2017

HotFixID=KB3155178

InstalledOn=5/15/2017

HotFixID=KB3156016

InstalledOn=5/15/2017

HotFixID=KB3156019

InstalledOn=5/15/2017

HotFixID=KB3159398

InstalledOn=5/15/2017

HotFixID=KB3161102

InstalledOn=5/15/2017

HotFixID=KB3161949

InstalledOn=5/15/2017

HotFixID=KB3161958

InstalledOn=5/15/2017

HotFixID=KB3170455

InstalledOn=5/15/2017

HotFixID=KB3170735

InstalledOn=5/15/2017

HotFixID=KB3172605

InstalledOn=5/15/2017

HotFixID=KB3177467

InstalledOn=5/15/2017

HotFixID=KB3179573

InstalledOn=5/15/2017

HotFixID=KB3

**Comment by zeffy** [comment]
Uh, it looks like the list you were copying got cut off. I'm going to need more info... Can you download [this](https://gist.github.com/zeffy/86accbe0b5ca265608b3a591936c81e4/archive/49bccb987f69fe03d1e58db5ecadffcab6d98ab3.zip), run show_debug_info.bat, and copy the text it opens in notepad into this issue?

Thanks.

**Comment by zeffy** [comment]
Hey again @jannos52, I just released a new patch version called wufuc which I believe may no longer have this issue. If you are still interested, could you please check it out and see if it works for you? Thanks. https://github.com/zeffy/wufuc/releases

**Comment by jannos52** [comment]
Thanks Zeffy

You are a legend! V2 you released worked great for me!


Janos

**Comment by zeffy** [comment]
Awesome. You're welcome, I'm glad to hear it works! I worked very hard on it. :)
