### ISSUE TITLE
Unsupported Hardware On FX Series CPUs

### ISSUE THREAD

**Issue by WillOfTheLand** [zeffy/wufuc#32]
FX 8350 Black edition shows the same error message, attempts at using your patch doesn't get anywhere anymore.

Ran into something interesting, running the patch got me to the point where it detects updates I can do on old CPUs, but win update always needs to restart before it will install them, which afterwords it will let me install security updates, but prevents all other updates such as silverlight, drivers, etc, from installing. And it's not that these are "new" updates, they're dated for 3 and 4 years ago.

**Comment by zeffy** [comment]
Can you download [this](https://gist.github.com/zeffy/86accbe0b5ca265608b3a591936c81e4/archive/49bccb987f69fe03d1e58db5ecadffcab6d98ab3.zip), run show_debug_info.bat, and copy the text it opens in notepad into this issue?

Thanks.

**Comment by zeffy** [comment]
Hey again @WillOfTheLand, I just released a new patch version called wufuc which I believe may no longer have this issue. If you are still interested, could you please check it out and see if it works for you? Thanks. https://github.com/zeffy/wufuc/releases
