### ISSUE TITLE
Windows 7 Home Premium

### ISSUE THREAD

**Issue by Jesus-37** [zeffy/wufuc#41]
Acabo de hacer una instalación nueva, y el parche no funciona correctamente no recibo actualizaciones, tengo un i5-7500

**Comment by zeffy** [comment]
Could you download the new version and try again? Thanks.  https://github.com/zeffy/wufuc/releases

---

(Google translated)

¿Podría descargar la nueva versión e intentarlo de nuevo? Gracias.  https://github.com/zeffy/wufuc/releases
