### ISSUE TITLE
Patch doesn't fool Intel Graphics Driver for Windows v15.45

### ISSUE THREAD

**Issue by davemc50** [zeffy/wufuc#42]
Clean install Win 7 on i7-7700K, with Asus H170 Pro Gaming.

Installs standard VGA graphics driver (ie performance index 1.0)

Intel Graphics driver download says for 7th Gen, only Win 10 supported (groan)

> This computer does not meet the minimum requirements for installing the software

I realise this is not directly related your neat patch Zeffy, it's just the next hurdle down the road after your fix nicely resolves patching issues.

**Comment by davemc50** [comment]
Asus beta alternate driver for HD630 [here](https://translate.google.co.nz/translate?hl=en&sl=zh-CN&u=https://www.asus.com.cn/support/Download/1/50/3/19/vYgO6z0aFlSTvvmE/30/&prev=search).

**Comment by zeffy** [comment]
I may look into this at some point, and make patches if it isn't too involved.

**Comment by navossoc** [comment]
You can disable the integrated graphics on the BIOS, this is probably the best idea.

[]'s

**Comment by jeneral** [comment]
If you don't want to use the Beta driver, follow post #24 on this thread:

https://www.sevenforums.com/general-discussion/405747-intel-g4560-kabylake-windows-7-64-bit-3.html

**Comment by Prodif** [comment]
For Windows 7 x64 Intel HD graphics driver, will warn about lack of the signature  )  WORK
https://yadi.sk/d/HfPC_FlK3K3NZr
