### ISSUE TITLE
wufuc64.dll missing??

### ISSUE THREAD

**Issue by munk1979** [zeffy/wufuc#45]
Installing on Windows 7 Pro 64bit. Run the installer and it creates and modifies the task. When it goes to start the task it errors out (see attached). I cannot find wufuc64.dll anywhere. Did I miss something prior to running the install?
![wufuc](https://user-images.githubusercontent.com/29259327/26892291-0ffc3d44-4b75-11e7-887c-f1a9d779c9f3.png)

**Comment by zeffy** [comment]
Hey there, it looks like you probably cloned the repository instead of downloading it from the releases page. Try getting it here it should work: https://github.com/zeffy/wufuc/releases

**Comment by munk1979** [comment]
That worked! It was human error as I assumed. Thanks!

**Comment by zeffy** [comment]
No problem, glad I could help! :)
