### ISSUE TITLE
But versions wufuc v0.6....0.6.0.2 not works for an Windows 7 x86 (32bit) (i3-7100)

### ISSUE THREAD

**Issue by Prodif** [zeffy/wufuc#47]
wufuc v0.6....0.6.0.2 not works for an Windows 7 x86 (32bit) (i3-7100)
wufuc v0.5rc2  perfekt works for Windows 7 x86 (32bit) (i3-7100)
wuaueng.dll  version 7.6.7601.23735 (oficial KB4019264)

**Comment by zeffy** [comment]
Thanks, I'm looking into this. Windows 7 and 8.1 x86 versions both use different patterns than the 64 bit versions, and I haven't been able to test the x86 versions yet so it is possible I made a mistake.

**Comment by zeffy** [comment]
I can confirm this issue on a VM, and it's actually causing the OS to freeze up for me, so **for now I would run the uninstaller and restart if you are able to**. 

I have a test environment set up for x86 now, so a fix should be out soon. I'm very sorry for the inconvenience. 

Off topic, but I should probably also add a kill key that can abort the patch procedure during boot for cases like this.

**Comment by Prodif** [comment]
No problems, i new instalation OS, 15 min on test mainboard. It is interesting to find a solution.

**Comment by zeffy** [comment]
I figured out the problem. In the x86 version of wuaueng.dll some offsets are stored differently (full address in x86 vs relative in x64). I was assuming it was relative too and adding it to a base address. So it was calculating and trying to alter the wrong offsets (probably out of range), and crashed the host process.

Working on fix now.

**Comment by zeffy** [comment]
Fixed it! I was also using incorrect pointer sizes. :weary:

I'll have a new release out shortly, nothing like this should happen again now that I have a x86 test VM set up.

**Comment by Prodif** [comment]
Support kb4022719 ?

**Comment by zeffy** [comment]
I will, yes. I just have to finish some last minute stuff before I make the new release. There was a lot of stuff broken in the utility scripts on x86, too.

**Comment by Prodif** [comment]
Can make two different distribution kits more simply, x86 & x64 )

**Comment by zeffy** [comment]
Should be fixed now. Tested on Windows 7 x86 and x64. https://github.com/zeffy/wufuc/releases

Thanks for reporting the issue!
