### ISSUE TITLE
Request for MSU packages (for use via DISM)

### ISSUE THREAD

**Issue by koitsu** [zeffy/wufuc#48]
This should be an enhancement/feature request of **very low** priority.

Issue #9 and pull request #46 document creation of an MSI file for "ease of installation".  However, there are those of us who "slipstream" drivers, KBs, service packs, into WIM files (boot.wim and install.wim) which are then used in a Windows 7 ISO or (more commonly) a bootable Windows 7 USB flash drive, all through use of DISM.  DISM doesn't support MSI files, but does support MSU and CAB files.  It would be useful to be able to incorporate wufuc into cmd/bat scripts allowing for a fresh OS install on a Kaby Lake/Ryzen system to run Windows Update out-of-the-box (no post-install steps).

A common methodology is the following:

mkdir mount
REM Windows 7 Ultimate x64 = index 4
dism /mount-wim /wimfile:install.wim /index:4 /mountdir:mount
REM Do other package and driver adds here, i.e. wufuc.msu should be *last*
dism /image:mount /add-package /packagepath:"wufuc\wufuc.msu"
dism /unmount-wim /mountdir:mount /commit
rmdir mount

The DLL patching should be doable, but the Task Scheduler job creation I'm not sure about.  Details I could find (I'm not a Windows sysadmin, just a UNIX one, so this is a bit out of my league): https://technobuff.wordpress.com/2008/07/22/what-is-an-msu-file/

Thank you!

**Comment by Prodif** [comment]
<settings pass="oobeSystem">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
				<FirstLogonCommands>
					<SynchronousCommand wcm:action="add">
						<Description>Description_of_command1</Description>
						<Order>1</Order>
                    <CommandLine>cmd /C %SYSTEMDRIVE%\Windows\Temp\WPI_64\WPI.exe</CommandLine>
					</SynchronousCommand>
					<SynchronousCommand wcm:action="add">
						<Description>Description_of_command2</Description>
						<Order>2</Order>
                    <CommandLine>cmd /C "%WINDIR%\Setup\Scripts\UAC.cmd" /f</CommandLine>
					</SynchronousCommand>
				</FirstLogonCommands>
		</component>
    </settings>
it is simpler to add in autounattend.xml )

**Comment by zeffy** [comment]
I'm a little confused. As far as I know, I can't make my own .msu can I? I assume they use some kind of certificate signing to verify they are from Microsoft. 

What @Prodif suggested should work, combined with removing the user input from the installer script should make for a pretty seamless deployment.

**Comment by zeffy** [comment]
Perhaps if someone wants to to share a copy-pasteable solution for integrating wufuc into  autounattend.xml I could add it to the repository so that other people have an easier time with it. Otherwise I'm going to go ahead and close this, since I can't really help any more than prodif already has.
