### ISSUE TITLE
Patch don't work

### ISSUE THREAD

**Issue by 2vic** [zeffy/wufuc#49]
Hotfix KB4022726 Windows 8.1 x64.

[aio-wuaueng.dll-patch.bat-debuginfo_2017-06-14_10-06-49_677000.txt](https://github.com/zeffy/wufuc/files/1073201/aio-wuaueng.dll-patch.bat-debuginfo_2017-06-14_10-06-49_677000.txt)

**Comment by zeffy** [comment]
Could you try the newest version here instead and see if it works? https://github.com/zeffy/wufuc/releases

Thanks.

**Comment by zeffy** [comment]
Ok I just verified, the latest version of wufuc should still work on Windows 8.1 x64 with KB4022726, so try it out.

**Comment by 2vic** [comment]
Thanks for the answer. I have established wufuc. {72EEE38B-9997-42BD-85D3-2DD96DA17307}. After loading of Windows the message on the unsupported equipment has disappeared. When checking updates this message doesn't appear too. I apologize for bad English.

**Comment by zeffy** [comment]
Don't worry, your English is good. :) 

It sounds like the patch is working as expected now, though! Let me know if you have any other problems.
