### ISSUE TITLE
Recent Windows Update!

### ISSUE THREAD

**Issue by LordSnax** [zeffy/wufuc#50]
I just downloaded Microsoft's latest security patches released on 6-12 and got the "Unsupported Hardware" message for the first time after restart. Strange as I never ran your patch before, and I have been using Windows 7 on my Ryzen system for about 3 to 4 weeks now. Well after Microsoft announced they were not supporting Windows 7 and 8 on next-gen hardware and was able to update fine. I think Microsoft released a new update that brings back the dreaded "Unsupported Hardware" message. The two updates I installed are, KB890830 and KB4022719. There was another update for Windows Defender (KB915597), but I do not think it is a concern.

Hope this helps,
Lord Snax

P.S. In case you are wondering, when I put my Ryzen system together. I moved the drives from my old AMD A10 system to my new Ryzen system without re-installing Windows 7. All I needed to do was install drivers and everything worked! I think that is why I never got the "Unsupported Hardware" message until now.

**Comment by zeffy** [comment]
Could you try the latest build for your platform here https://ci.appveyor.com/project/zeffy/wufuc and see if it works?

I updated my Windows 7 test environment and wufuc persisted through KB4022719 and I can still check for updates without any errors.

**Comment by LordSnax** [comment]
I just downloaded the latest patch prior to posting this thread. I was just giving you a heads up. As this was the first time I received the "Unsupported Hardware" message. Thanks for the input though.

Lord Snax

**Comment by LordSnax** [comment]
Yup! Looks like it worked. Got the "No important updates available" message for windows update. I will let you know if I run into the "Unsupported Hardware" message again.

Thanks for making the patch. I am a hardcore Windows 7 and AMD fan,
Lord Snax

**Comment by zeffy** [comment]
So it is working again, then? Good to hear it. Kind of wonder what caused it to hiccup earlier though?

**Comment by zeffy** [comment]
Just released a new version, check it out! Tested and working with the new updates. https://github.com/zeffy/wufuc/releases

**Comment by LordSnax** [comment]
I never ran the patch before. I think the reason behind why I never got the "Unsupported Hardware" message until now, is because the update that checked for the next-gen hardware was installed when I was using my old PC. 

I think Microsoft released another update that scanned for the next-gen hardware again. As I think they realised that you can move an entire Windows installation from one computer to another by swapping the hard drives. As long as the hardware is similar. As in my case I went from a pc using an A10-6800K to a pc using a Ryzen 5 1600. All I had to do was install the drivers for the new system

Lord Snax

**Comment by zeffy** [comment]
Oh I misunderstood you before, sorry. Yes, you are correct in that Microsoft pushes the file responsible for the cpu check with every monthly quality rollup.

But the issue you were having earlier is now cleared up, correct? Just to be clear.

**Comment by LordSnax** [comment]
Yes, it is cleared up. Everything works as expected.

Have an awesome week,
Lord Snax
