### ISSUE TITLE
IDP.ALEXA.51 trojan detection (with AVG) when installing wufuc64.dll from 0.6.0.2

### ISSUE THREAD

**Issue by stevemoreau** [zeffy/wufuc#51]
Hi guys, the latest wufuc 0.6.0.2 is being quarantined by AVG when running the batch file.
Not sure you can prevent that, but if there is a workaround please share !
Thanks for the great job,

![image](https://user-images.githubusercontent.com/16148036/27119353-d71e35fc-50df-11e7-9480-9eebbce3a393.png)

**Comment by zeffy** [comment]
Well, considering how wufuc works, that's not really surprising. I assure you it isn't doing anything that isn't absolutely necessary to restore updates. If you're worried about the warning you can always review and compile from source! ;)

For now the only thing you can really do is make an exception for it. If this becomes a real problem I could try getting it white-listed by AV vendors, I guess?

**Comment by zeffy** [comment]
Tbh it's really weird that your AVG detects it, I just scanned 0.6.0.2 on virustotal and it got 0/60, even with AVG: https://www.virustotal.com/en/file/6f02c285f47fb93907090767226ec27c1f21955f414536286e8672ce316bc187/analysis/1497424882/

**Comment by stevemoreau** [comment]
Thanks, yep I have created an exception but I was wondering if you were aware of a workaround to avoid falling into this case at each new update (for example, "avoid running from Downloads directory"). But, I'll live with AVG exception without problem :)
To answer your last question, it seems it complained about the way it was installed if I remember the message correctly. That's why I suspected some kind of origin test or so. Anyway, that's not a big deal.
See you

**Comment by zeffy** [comment]
Oh I see what you're saying now! Well you could try moving the files to a more permanent folder like `C:\Program Files\wufuc` before installing them, also maybe go to the properties on the wufuc files after you extract them and "Unblock" them (see here http://www.thewindowsclub.com/fix-windows-blocked-access-file).

See you! Always glad to hear feedback from people using my work. :)

**Comment by rautamiekka** [comment]
I think AVG is doing its job correctly **this time**: http://acronyms.thefreedictionary.com/IDP says `IDP` could stand for `Intrusion Detection and Prevention`, which matches the way wufuc functions, so assuming AVG is using a heuristic or similar on something shipped with wufuc, it's not a surprise.

**Comment by zeffy** [comment]
Yes, I agree. While it is absolutely a false positive because the things wufuc does are desired by the user,  under other circumstances what it does appear very suspicious to an AV.

**Comment by stevemoreau** [comment]
Tried the 0.6.1 version right now, after unblocking the ZIP file via Windows Explorer > _right click on the ZIP file_ > Properties > Unblock, and everything went all right with AVG this time. Cool !

**Comment by zeffy** [comment]
Nice! Maybe they got wise. :stuck_out_tongue_winking_eye:
