### ISSUE TITLE
Unable to run the windows update

### ISSUE THREAD

**Issue by Subash023** [zeffy/wufuc#52]
Unsupported hardware error has come. unable to run your patch file also.  Log file has created in notepad. Please help me to resolve this issue.
[aio-wuaueng.dll-patch.bat-debuginfo_2017-06-14_15-22-00_015000.zip](https://github.com/zeffy/wufuc/files/1074234/aio-wuaueng.dll-patch.bat-debuginfo_2017-06-14_15-22-00_015000.zip)

**Comment by zeffy** [comment]
Hey there, it looks like you're still using the old patch script!

I just released a new version of my new patching method, which is different from what you are currently using. See the [project page](https://github.com/zeffy/wufuc) for more information about the differences.

Basically it solves all the issues with the old patch. It also supports these new update KB4022719 that you're talking about. Check it out! https://github.com/zeffy/wufuc/releases

**Comment by Subash023** [comment]
Hi i run the new release from https://github.com/zeffy/wufuc/releases. But the same message has come again. Unsupported hardware. If i run check for updates the error has come like Windows could not search for new updates. Please help me how to disable the Unsupported Hardware message and how to allow them for more updates.

**Comment by zeffy** [comment]
The patch should 100% be working in your case, so I'm not sure what's wrong.

What does it say when you run `install_wufuc.bat`, can you copy paste that here, please?

**Comment by Subash023** [comment]
Hi i have attached the screen shot. please find the screen shot for your reference.
[Windows Update Error.zip](https://github.com/zeffy/wufuc/files/1074857/Windows.Update.Error.zip)

**Comment by zeffy** [comment]
Is it possible the patch is working but you are getting some other error? Because that's a different error code (`80072EE2`) than what usually shows up for me (`80240037`). 

Can you confirm if the Unsupported Hardware message window definitely is showing up after patching?

**Comment by zeffy** [comment]
Also if you get a chance, can you read the new issue guidelines [here](https://github.com/zeffy/wufuc#reporting-an-issue-) and reply here with the requested information? It would really help me out, thanks.

**Comment by mungo1147** [comment]
Hi, Used your patch v0.5rc2 about 4 weeks ago and that fixed the "unsupported Hardware" Message . Came back today with KB40222719. Ran your latest wufuc v0.6.1 everything appears to be OK  can access update centre again. Fantastic Thanks

**Comment by Subash023** [comment]
After i run the repair patch file now i am not getting the unsupported hardware message. Now it is working fine. But i can update it via online not by our WSUS server.

**Comment by zeffy** [comment]
@mungo1147 Very happy to hear it!

@Subash023 I'm glad that seems to have resolved it. I don't use WSUS, however unless WSUS immediately starts working again after disabling wufuc and restarting your PC, I don't think the problems you're having with it are because of my patch. Is it possible something else is causing it?

**Comment by zeffy** [comment]
Closing this for now since the issue seems to be fixed by repairing wuaueng.dll. Please let me know if either of you need additional help.
