### ISSUE TITLE
Unsupported Hardware (again)

### ISSUE THREAD

**Issue by Moltresrider** [zeffy/wufuc#54]
The wufuc got broken again! I got a "unsupported hardware" message on my Sandy Bridge PC(Looks like Microsoft hasn't fixed the bug with older model PC's yet). I tried running the patch from my last bug report on this issue but that did not fix the problem

**Comment by zeffy** [comment]
Hey there @Moltresrider, sorry you're having problems again.

I just wrote up some issue reporting guidelines which should assist you in helping me resolve your issue. :)

Please read them and reply back with the information requested. https://github.com/zeffy/wufuc#reporting-an-issue-

**Comment by zeffy** [comment]
Also, consider running `utility scripts\repair_wuaueng.dll.bat` and rebooting, someone else was having a similar issue to you and that fixed it.

**Comment by zeffy** [comment]
I'm going to assume this issue was resolved since there's been no reply for seven days. If you're still having this issue please try the suggestions in the link above and reply back with the information requested if nothing helps and I'll open it again. Thank you.
