### ISSUE TITLE
wufuc64.dll is infected by IDP.ALEXA.51

### ISSUE THREAD

**Issue by saki117** [zeffy/wufuc#55]
My antivirus software said that the file wufuc64.dll is infected by IDP.ALEXA.51 , I cannot get it installed.

I am using avast free antivirus. There are no this issue with the last release.

**Comment by rautamiekka** [comment]
This was here just recently, and it's a false positive. `IDP` means `Intrusion Detection and Prevention` but the name `Alexa.51` ain't explained although it also seems to be a name for a valid detection.

AVG (the first report) and Avast are doing their job right by noticing wufuc is using special means to bullshit the OS, so you need to put wufuc's folder into global exclusion: open Avast's settings dialog and add the full path to the 'Exclusions' dropdown menu in the middle.

**Comment by saki117** [comment]
Thanks for the explanation! It works now!
