### ISSUE TITLE
MCUpdate getting disabled

### ISSUE THREAD

**Issue by jeneral** [zeffy/wufuc#58]
The main reason I use Windows 7 is because of Windows Media Center. I notice the latest release of this patch disables the mcupdate_scheduled task on restart. This stops MC from getting guide updates automatically. A few other MC tasks are affected but this one causes the most problems. 

I now enable the task manually after restarts. Can this behavior be changed? ATM MS doesn't cripple MC on Kaby Lake systems.

**Comment by zeffy** [comment]
Weird, nothing in wufuc should be messing with WMC or other scheduled tasks at all. Are you sure it is responsible? If you uninstall wufuc does this problem go away?

**Comment by zeffy** [comment]
@jeneral did you ever get wufuc working?

**Comment by jeneral** [comment]
Close this thread. I uninstalled wufuc and restarted a few times. Every time I restart that task gets disabled. I'm not sure what is causing this.

**Comment by zeffy** [comment]
So strange. Best of luck though, I hope you are able to figure it out.
