### ISSUE TITLE
Stopped working after recent update

### ISSUE THREAD

**Issue by Echtze1t** [zeffy/wufuc#59]
Hello,

I installed your patch on my system last week and the error message disappeared, but after I updated last night, it's back again and your patch asked me to post the error log here.

...

For whatever reason, github won't let me upload it, so I put it in my cloud shares.

[https://mega.co.nz/#!qYUnACqB!AAAAAAAAAADiEgw5PXuW2QAAAAAAAAAA4hIMOT17ltk](url)

**Comment by zeffy** [comment]
Hi, you closed this already, so I assume you found the new version? If not, grab the latest release, it should fix any issues you are having. https://github.com/zeffy/wufuc/releases
