### ISSUE TITLE
I can´t make it work. 

### ISSUE THREAD

**Issue by marcioishii** [zeffy/wufuc#60]
I use a preview wufuc_v0.6.1 and it worked fine. But after a windows actualization I installed wufuc_v0.6.1.22 but I still receiving the windows message. 

[728] 
[728] APISVR_ERROR : 2
[728] 
[728] APISVR_INFO : 2
[728] 
[728] APISVR_INFO : 2

**Comment by marcioishii** [comment]
Never mind, I made it work! Thanks! =D

**Comment by zeffy** [comment]
Glad you got it working, let me know if you have any other issues or questions! :)
