### ISSUE TITLE
64 bit?

### ISSUE THREAD

**Issue by KellyDodge** [zeffy/wufuc#67]
So, I downloaded version 0.6.1.22 for my machine. It recognizes that I am running Windows 7 in 64 bits. It tries to do the rundll command, but it says that it can't find the target dll.  Quickly looking at the BAT file, it seems like it is looking for a wufuc64.dll instead of a wufuc32.dll....

For grins, I tried renaming the 32 file as a 64 file, but it doesn't seem to be working.

Ideas?

Thanks!

-Kelly

**Comment by KellyDodge** [comment]
So I saw on another issue something that looked similar. I downloaded wufuc_v6.1.28-fea921d3_x64. It seems to install with no issues, but I still get the Unsupported Hardware issue.

**Comment by KellyDodge** [comment]
So, I uninstalled everything, rebooted, reinstalled, and now it works fine. Thank you!

-Kelly

**Comment by zeffy** [comment]
If you downloaded the release from [here](https://github.com/zeffy/wufuc/releases), it definitely should have come with wufuc64.dll too. Is it possible your antivirus flagged and deleted it?

Kind of weird that you still got errors after installing the appveyor build though, as it shouldn't be necessary to restart. I may have to look into that, but I'm glad the is working for you now.
