### ISSUE TITLE
zip distribution

### ISSUE THREAD

**Issue by jjurkus** [zeffy/wufuc#73]
Would it be possible to also keep the zip distribution, as with the older versions?
I have made a script for my deployment software that uses the seperate files. With MSI files I have to extract these files from the MSI, which is possible, but takes a lot more time than a simple zip file.

**Comment by AnonUser95** [comment]
I was thinking the same. I'm unsure whether to continue with v0.7.0.58 or v0.7.0.43. The file type has changed and the newest version installs directly. Please stick with ZIP files, zeffy. Allows for easier access to the version files.

**Comment by rautamiekka** [comment]
The MSI is likely made through an automated script anyway, so a ZIP wouldn't be much of a problem.

**Comment by zeffy** [comment]
@jjurkus @AnonUser95 Thanks for the feedback. I will add the zip distribution back. You can actually still get the zip bundles from [AppVeyor](https://ci.appveyor.com/project/zeffy/wufuc), but I'll add them to the release page too. :)

**Comment by jjurkus** [comment]
Thanks, that would be great!

**Comment by zeffy** [comment]
New release posted that includes the unified zip package, which has the same file naming format as previous versions, so you should be able to transition to it without any hassle. https://github.com/zeffy/wufuc/releases
