### ISSUE TITLE
No "Unsupported Hardware" pop up (7th Gen CPU)

### ISSUE THREAD

**Issue by AnonUser95** [zeffy/wufuc#74]
I'm not sure if this is unusual or not, but after I uninstalled a slightly older version to install a new one after restarting the PC, I left it to see if I would get the same pop up but I haven't. Rather odd since I use a 7th Gen CPU and have been using wufuc which has helped a lot. I will probably have to keep wufuc installed/updated because I probably won't be able to continue updating Windows 7 without it. I haven't experienced any problems though because of it, just seems strange. Hopefully nothing to worry about.

**Comment by zeffy** [comment]
That's normal, I designed the disable/uninstall scripts so that the patch would stay active and only unload wufuc.dll. To fully undo the patch you can either restart the wuauserv service or restart your computer, and you will start getting the popup again.

**Comment by AnonUser95** [comment]
Thank you for the reply. When I did restart however after uninstalling, I didn't get the pop up. I did try a few times to see if I could prompt it but oh well. I guess I should just install the new version anyway.

Also one last question, do we need to keep updating to a newer version every time? I mean as long as the version we have works fine for the user without problems, is it mandatory? Or is it okay to wait for later versions?

**Comment by zeffy** [comment]
Huh, that's kind of weird. The message should pop up when you check for updates. You're sure the wufuc scheduled task is disabled?

At this point most of the new releases are just minor bug fixes or performance improvements, like fixing memory leaks etc. The 0.7.0.43 release and all the builds after that should be mostly ok. 

The new releases should start to slow down now anyway, as long as no serious issues come up.

**Comment by AnonUser95** [comment]
I just went ahead and uninstalled in administrator mode then restarted, so that I could go ahead and install the new file. I don't think I disabled wufuc. Also it's most likely because I couldn't check for further windows updates as I already had all the recent ones installed, meaning everything is up to date. Might be why it hasn't popped up... possibly. But I've just installed the recent version so everything should be good. Also thanks for the heads up.

**Comment by zeffy** [comment]
Oh I see, yeah the scheduled task would have been deleted if you uninstalled. Like you said, it's probably because it didn't check for updates. 

Normally the pop up would get triggered either when Windows Update does its scheduled check, or when you do it manually by clicking "Check for updates" here:
![explorer_2017-07-04_15-42-04](https://user-images.githubusercontent.com/10877719/27843959-7c43791c-60cf-11e7-8a45-b6a5fba0b89f.png)

Glad everything's working as expected for you, though! :)
