### ISSUE TITLE
Message about unsupported hardware

### ISSUE THREAD

**Issue by 2vic** [zeffy/wufuc#77]
Hello. When you turn on your computer, a message appears on an unsupported hardware, when you restart-No. The way it should be?

**Comment by zeffy** [comment]
Ideally you shouldn't have to restart to activate the patch, but some people do have to. But please read the [contributing guidelines](https://github.com/zeffy/wufuc/blob/master/CONTRIBUTING.md) and reply here with all the requested information and I will be able to offer you more assistance.

**Comment by 2vic** [comment]
Hello. After installing wufuc v0.7.0.62 x64, when you turn on the computer, a window appears about unsupported hardware. In this case, Windows Update works. Apparently, the planned wufus task is included later.
On the version of wufuc v0.6.1.22 and earlier this was not.

**Comment by zeffy** [comment]
Interesting. Can you try using the .zip package for 0.7.0.62 instead? The MSI installer uses a slightly different way of installing the scheduled task, so that may be why it is different. I will look further into this.
