### ISSUE TITLE
Another older model Processor that needs to be added to the wrongly detected processors in the readme

### ISSUE THREAD

**Issue by Moltresrider** [zeffy/wufuc#80]
The computers that the clients use where I work and the ones where my job is to troubleshoot. They are all HP Pavilion Slimline s7520n PC machines and 3/7 machines are giving the Unsupported Hardware message.

These are all running Windows 7, and as a matter of fact, Windows 7 is not even officially supported on these machines. So Windows 10 is definitely not supported. How could Windows 10 even run on a computer that is 1GB ram and can only go up to 2GB.

the processor in question is: Processor	AMD Turion(tm) 64 Mobile Technology ML-34, 1800 Mhz, 1 Core(s), 1 Logical Processor(s)

As you can probably know by looking at the name, Windows 10 cannot run on something _this_ old.

**Comment by zeffy** [comment]
Added! Thanks for letting me know.
