### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by ldlx** [zeffy/wufuc#81]
Hi,

it's easy to automate the batch installer. If you want to create an installer, please use Windows Installer (e. g. WiX), but not Advanced Installer. If you like to use WiX and need help creating an installer based on it, I'm happy to help you - of course the batch files do their job.

**Comment by zeffy** [comment]
Hi there. May I ask why is Advanced Installer not acceptable?

**Comment by ldlx** [comment]
Advanced Installer is used to create Windows Installer packages as well, but they are not "standard" MSI files - this could lead to problems with group policy deployments, creating transforms and so on. With WiX you can create packages that will behave like a standard MSI package (and with it, no problems with installation/repair/uninstallation and creating transforms for the package).
Although you can do "custom things" with a Windows Installer package (like scripting or injecting custom actions), a Windows Installer package defines a state of an installed/uninstalled product and should not be used as a replacement for a scripted installation/uninstallation (similar to Nullsoft Installer).

**Comment by ldlx** [comment]
Btw. WiX is open source and integrates with Visual Studio. To begin with WiX, you can use this tutorial: http://www.tramontana.co.hu/en.
I experienced problems with Advanced Installer MSI packages some years ago with CDBurnerXP where I wasn't able to customize the group policy deployment. So I created a Windows Installer package built with WiX, discussed it with the developer and finally it was adopted and integrated into the build process for the Windows Installer packages of CDBurnerXP.

**Comment by zeffy** [comment]
I'm going to stick with Advanced Installer; they were kind enough to sponsor my project by giving me a free open source license for their software, and IMHO it's much easier to use in comparison to Wix.

I'm not very familiar with how group policy deployment works however, so are you saying there's something specific that is making the current MSI setup non-viable for use with GP deployment?

**Comment by ldlx** [comment]
Ah ok, I understand. 

So when you install it in GUI mode, you can change features, directories and so on (this also works with Advanced Installer, but non-standard)). When you deploy using group policy you have to use transform files to customize the installation, which didn't work well with the old Advanced Installer package of CDBurnerXP (enabling/disabling features, modifying directories like start menu folder or changing/removing shortcuts).

One thing to notice for Windows Installer is that different actions are executed in different user contexts. With group policy the installation is done using the system account. When installing through GUI starting Msiexec.exe and some actions can be done using the (non-elevated) user account, some actions request elevation during installation.
