### ISSUE TITLE
Current update from MS re-trigger the cpu check

### ISSUE THREAD

**Issue by DBynum1** [zeffy/wufuc#88]
After installing current July/2017 updates, the "incompatible cpu" nagware has reasserted itself.
OS is Win 7, kabylake I7 7th gen processor.
Installed updates:
kb4024848  kb4025341  kb4019990

I do not know which of these is the culprit. If there is a more appopriate location for this post,
please relocate it, thank you.

**Comment by zeffy** [comment]
Hi sorry for the delay. kb4025341 is the last update to come out which modifies wuaueng.dll, and it should still be supported as far as I know. Could you read the [contributing guidelines](https://github.com/zeffy/wufuc/blob/master/CONTRIBUTING.md) and reply with the information requested there, including the .log files in wufuc's install folder? Thanks.

**Comment by zeffy** [comment]
Closing due to lack of response and information.
