### ISSUE TITLE
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT

### ISSUE THREAD

**Issue by Noizcontroller** [zeffy/wufuc#89]
Hi

When I run the script it fails with an xdelta 3 error which says that the input file is invalid. However I didnt tamper with the dll of the Windows Update service. I'm getting this error on 20+ clients. Every client has 1 of the KB's installed which block the execution of the recent Windows Updates. I included the log file and command prompt content.

[Command prompt.txt](https://github.com/zeffy/wufuc/files/1167338/Command.prompt.txt)
[aio-wuaueng.dll-patch_install.bat-debuginfo_2017-07-22_13-42-42_707000.log.txt](https://github.com/zeffy/wufuc/files/1167339/aio-wuaueng.dll-patch_install.bat-debuginfo_2017-07-22_13-42-42_707000.log.txt)

**Comment by zeffy** [comment]
Hey there, it looks like you're using an older version (<0.6) of wufuc, please download the [**latest version**](https://github.com/zeffy/wufuc/releases) (wufuc_setup_x64.msi) and try it out. It should solve any problems you are having. You may have to restart to fully remove the old patch after you install the new one.

For more information about how the new patch works, see the [README](https://github.com/zeffy/wufuc#how-it-works).

I'm going to close this issue for now, but if you have any more questions or issues please feel free to reopen it.
