### ISSUE TITLE
Create MSI installer using Wix to deploy the patch via group policy

### ISSUE THREAD

**Issue by RussianBarbarian** [zeffy/wufuc#9]
This script should not be interactive for GP automation. Now I'm making a decision for a corporate infrastructure based on logon-script.
In addition to interactivity, changes are made to the:
takeown /F "%WUAUENG_DLL%" /A
logon-script use local system acсount, so we use
takeown /F "%WUAUENG_DLL%"
and add rights for local system
icacls "%WUAUENG_DLL%" /grant *S-1-5-18:F

**Comment by zeffy** [comment]
After thinking about this for a while, I don't think I will add this to the project it because would be very difficult to debug if there are any issues, and many changes would have to be made to this script in order to output to a log file. I also prefer not to have to maintain two separate scripts.

However, I'm going to leave this issue open so anyone interested can find your changes if they want to use them. Keep in mind that you deploy this in a corporate environment at your own risk.

**Comment by zeffy** [comment]
I may re-evaluate this now that I've added debug log generation. GP automation could possibly be integrated into the main script with a command line argument like /unattended.

**Comment by zeffy** [comment]
Actually, I'll probably just solve this issue with my new service-based solution by providing an MSI installer that can be deployed through group policy.

**Comment by tfc1974** [comment]
Hi Zeffy, first off the new service patched worked flawlessly and I finally am up to date, so THANK YOU, it's really awesome what you've done. My only question here in regards to cooperate/ enterprise environments is is this an issue when enterprises patch via WSUS servers? I thought I had read somehow it would not affect machines tied to WSUS? Have you heard this??

**Comment by zeffy** [comment]
@tfc1974 I'm happy you like it! :) 

I've read conflicting information regarding that, but I think most people say WSUS is affected by the CPU check, just like Windows Update. I don't use WSUS though, so I couldn't say for sure.

**Comment by tfc1974** [comment]
I *think* because the wsus server is doing the downloads and talking to the MS servers and the win7 workstations are only talking to wsus the issue does not occur. Check this link out:
http://www.nag.co.za/2017/03/16/windows-7-and-8-1-kaby-lake-and-ryzen-systems-are-unsecure/

**Comment by zeffy** [comment]
I can't say for WSUS but even if you manually download `.msu` packages and try installing it, it will fail with the error code `0x80240037` which is the same error you get in Windows Update after getting the unsupported hardware message. The check is a part of the core update engine. I don't think WSUS bypasses it either. I could be wrong though.

**Comment by tfc1974** [comment]
Good to know about the msu packages. I'll try to verify at work as we have some newer hardware that we will be imaging with Win7x64 and we use wussy for updates. There's also some postings out there suggesting certain MS patches, 2 in particular, are actually responsible for this whole mess, not sure how accurate that is but saw on MS forums and some other site.

**Comment by winterheart** [comment]
Hello, @zeffy! Still need help with MSI packaging?

**Comment by zeffy** [comment]
Absolutely! Are you interested in helping?

**Comment by BergischNRW** [comment]
@tfc1974 We use a WSUS server and just bought a device with a 7th-gen i7. We get the popup with "unsupported device detected". After installing wufuc with the batch script, everything worked.
So sadly WSUS is also effected.

**Comment by rpm9** [comment]
Found your Kaby solution and just thinking out loud here, but you might not need an MSI.  I'll explain and you can let network admins decide if this is a reasonable solution.  wufucXX.dll could be placed in a folder in the same structure from where their MSIs are normally deployed.  It can live on a server and does not have to be deployed to workstations.  Then, via GPO, deploy just the scheduler item that points to wufucXX.dll on the server.  When your dll is updated, admins just overwrite it - done.

**Comment by zeffy** [comment]
@BergischNRW Thanks for clearing that up, it is nice to know for sure that WSUS doesn't bypass the check.

@rpm9 You're correct, it should be possible to deploy it the way you described, but I was wanting to make a proper installer for wufuc anyway, so I figured it might as well use MSI and tackle this issue at the same time. @winterheart started the implementation, but I haven't heard from him in a while. I'm probably going to see if I can finish what he started and get the changes merged in. Could be a while though, because I don't really know much about Wix.

**Comment by rpm9** [comment]
Having the option of installing via MSI will be great.  In the interim, another method I tried was just copying (using update in the GPO) wufuc to C: and setting the scheduler to run it.  Since wufuc is locked by svchost, the GPO update does not work.  Solution was unique filenames. I just included your version # in wufuc.  The GPO has 3 items   1. delete obsolete wufuc64-v1234.dll  2. copy new wufuc64-v6122.dll  3.  Schedule wufuc64-v6122.dll.   This works but the GPO will need tweaking each time you update wufuc.  Can wufuc be unlocked?  If that was possible, only the update & schedule items would be necessary and the GPO would be set and forget.  Your dll updates would just need to be copied to a server.

**Comment by rautamiekka** [comment]
^ If http://www.softpedia.com/get/System/System-Miscellaneous/Unlocker.shtml and IObit Unlocker can ...

**Comment by zeffy** [comment]
@rpm9 I have an unload procedure built into wufuc that I use in my current uninstaller scripts, you can trigger it by running `rundll32 "C:\path\to\wufucXX.dll",Rundll32Unload` as administrator. This will unload it from svchost.exe so you can update/delete it. :)

**Comment by zeffy** [comment]
@rautamiekka It is very dangerous to force unload wufuc from svchost.exe that way because it won't be able to clean up its `LoadLibraryEx` hooks before it unloads, which will cause svchost.exe to hang or completely crash the next time it tries to load a dll (such as when a service starts).

**Comment by zeffy** [comment]
@winterheart has finished the wix project! :) 

I'll need to review it and make some adjustments before it is released, but you should be able to expect MSI installers with the 0.7 release once I finish #66.

I'm going to close this issue, but feel free to continue discussion if necessary.

**Comment by rautamiekka** [comment]
^ I were thinking along the lines of unlocking whatever files were being held locked and thus preventing updating wufuc.

**Comment by zeffy** [comment]
@rautamiekka Yes, I know exactly what you were talking about and like I said, it is very dangerous to do that. "Unlocking" files will force svchost.exe to close its open handle on wufucXX.dll (or will just straight up kill the svchost.exe process) which will eventually cause it to totally crash. Please use the method I posted above to safely unload wufuc instead.

**Comment by rautamiekka** [comment]
^ So it's either total kill or nothing, there's no middle ground ? I read you've only that with process termination on Window$ with Task Manager, or in general.

**Comment by zeffy** [comment]
????? No, that is not what I'm saying! Please read:
> I have an unload procedure built in to wufuc that I use in my current uninstaller script, you can trigger it by running `rundll32 "C:\path\to\wufucXX.dll",Rundll32Unload` as administrator. _**This will safely unload it from svchost.exe so you can update/delete it**_.

**Comment by zeffy** [comment]
I just released the new MSI installers for x64 and x86!! https://github.com/zeffy/wufuc/releases

Please let me know if any of you encounter any issues with them, and I'll try to get it fixed as soon as I can.

**Comment by H-Steel** [comment]
I’m trying to deploy wufuc via GPO, but I have a error massage. Error code 1605.
Here are windows installer logs:
=== Verbose logging started: 30.07.2017  19:06:33  Build type: SHIP UNICODE 5.00.7601.00  Calling process: C:\Windows\system32\svchost.exe ===
MSI (c) (58:48) [19:06:33:889]: User policy value 'DisableRollback' is 0
MSI (c) (58:48) [19:06:33:889]: Machine policy value 'DisableRollback' is 0
MSI (c) (58:48) [19:06:33:889]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (c) (58:48) [19:06:33:889]: Executing op: Header(Signature=1397708873,Version=500,Timestamp=1258197986,LangId=1028,Platform=589824,ScriptType=3,ScriptMajorVersion=21,ScriptMinorVersion=4,ScriptAttributes=0)
MSI (c) (58:48) [19:06:33:904]: Executing op: ProductInfo(ProductKey={2F696F74-0FD5-49E1-BEEC-A4256F6D7404},ProductName=wufuc,PackageName=wufuc_setup_x64.msi,Language=1028,Version=458753,Assignment=1,ObsoleteArg=0,,,PackageCode={3E0655BA-1CD2-47E0-A7E1-D13727718241},,,InstanceType=0,LUASetting=0,RemoteURTInstalls=0,ProductDeploymentFlags=3)
MSI (c) (58:48) [19:06:33:904]: Executing op: DialogInfo(Type=0,Argument=1028)
MSI (c) (58:48) [19:06:33:904]: Executing op: DialogInfo(Type=1,Argument=wufuc)
MSI (c) (58:48) [19:06:33:904]: Executing op: RollbackInfo(,RollbackAction=Rollback,RollbackDescription=正在復原操作:,,CleanupAction=RollbackCleanup,CleanupDescription=正在移除備份檔案,CleanupTemplate=檔案: [1])
MSI (c) (58:48) [19:06:33:904]: Executing op: ActionStart(Name=PublishFeatures,Description=正在發佈產品功能,Template=功能: [1])
MSI (c) (58:48) [19:06:33:904]: Executing op: FeaturePublish(Feature=MainFeature,,Absent=0,)
MSI (c) (58:48) [19:06:33:904]: Executing op: ActionStart(Name=PublishProduct,Description=正在發佈產品資訊,)
MSI (c) (58:48) [19:06:33:904]: Executing op: CleanupConfigData()
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\UserData\S-1-5-18\Products\47F696F25DF01E94EBCE4A52F6D64740\Patches 3: 2 
MSI (c) (58:48) [19:06:33:904]: Executing op: ProductPublish(PackageKey={3E0655BA-1CD2-47E0-A7E1-D13727718241})
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:904]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740 3: 2 
MSI (c) (58:48) [19:06:33:920]: Executing op: UpgradeCodePublish(UpgradeCode={4C52972C-251E-4D1B-AD09-EAA765719DCC})
MSI (c) (58:48) [19:06:33:920]: Executing op: SourceListPublish(,,DiskPromptTemplate=[1],,NumberOfDisks=1)
MSI (c) (58:48) [19:06:33:920]: Note: 1: 1402 2: UNKNOWN\Installer\Products\47F696F25DF01E94EBCE4A52F6D64740\SourceList 3: 2 
MSI (c) (58:48) [19:06:33:920]: Executing op: ProductPublishClient(,,)
MSI (c) (58:48) [19:06:33:935]: Executing op: End(Checksum=0,ProgressTotalHDWord=0,ProgressTotalLDWord=0)
MSI (c) (58:48) [19:06:33:967]: DoAdvertiseScript is returning: 0
=== Verbose logging stopped: 30.07.2017  19:06:33 ===

May be a reason in language settings, I’m trying to deploy it to Russian language OS, Windows 7 64-bit.
