### ISSUE TITLE
Nagging has returned.

### ISSUE THREAD

**Issue by DeScruff** [zeffy/wufuc#90]
I only recently upgraded to a Ryzen based PC, and I keep randomly getting the Microsoft nagging.
I am using the latest version of wufuc,, v0.7.1.81, and have tried reinstalling the software, and restarting the computer, however the nagging is fairly random.

The only new update since the upgrade to Ryzen was KB4032113, prior to the upgrade I did install KB890830, and KB4025341. - I dunno which updates would be relevant.

Side note: I had to put my install folder in a different location then the default C:/Program Files otherwise log files would not be created... If thats normal, that should probably be noted somewhere for those with no idea what they are really doing like me... 
- Also github didn't want to take the .log files, so I had to manually make them .txts

[wufuc.rundll32.exe.txt](https://github.com/zeffy/wufuc/files/1168408/wufuc.rundll32.exe.txt)
[wufuc.svchost.exe.txt](https://github.com/zeffy/wufuc/files/1168410/wufuc.svchost.exe.txt)[](url)

**Comment by zeffy** [comment]
Thank you for your issue report. It's probably KB4025341. I think some other people may also be having this problem.

>Side note: I had to put my install folder in a different location then the default C:/Program Files otherwise log files would not be created... If thats normal, that should probably be noted somewhere for those with no idea what they are really doing like me...

That's not normal. wufuc runs as the SYSTEM user, so it should have access to write in most places, including Program Files. This leads me to believe it's possible the task isn't being set up correctly, but I can't be sure. It could be an issue with the MSI installer, could you try installing wufuc from the .zip package instead and see if it works?

**Comment by DeScruff** [comment]
Ok, Ive manually installed it from the .zip.
So far the nagging has stopped, and the log files are being updated every time I restart!

**Comment by zeffy** [comment]
Interesting. The MSI and batch installers set up the task slightly differently, so that may explain it. I think I'm going to work on emulating the batch installer behavior in the MSI instead. 

Glad the zip is working correctly for you. Thanks again for reporting this.

**Comment by qgtxqj** [comment]
same situation as @DeScruff, and also soveld by removing MSI installation and reinstall wufuc from the zip. The returned nagging was away from me now. amazing!
