### ISSUE TITLE
Win patches

### ISSUE THREAD

**Issue by dpak4u** [zeffy/wufuc#95]
https://github.com/zeffy/kb4012218-19

Can you please share updates working for 2012 r2 and 2008R2 as well ?

**Comment by zeffy** [comment]
The [latest version](https://github.com/zeffy/wufuc/releases) should be compatible with 2012 R2 and 2008 R2, what's not working for you? Could you give me more information?

**Comment by zeffy** [comment]
Closing due to lack of response and information.
