### ISSUE TITLE
wuaueng.dll is below minimum...

### ISSUE THREAD

**Issue by adminsly** [zeffy/wufuc#97]
when i try to start the program it give me 
error... wuaueng.dll is below minimum...

what this mean ? i use your program before and never had this one.

thanks 

sylvain

**Comment by zeffy** [comment]
Can you check what version your `C:\Windows\System32\wuaueng.dll` is and let me know? This shouldn't happen unless you don't have any updates installed that have the cpu check. Also, if this is indeed in error, you could try the .zip installer package instead of the .msi.

**Comment by adminsly** [comment]
sorry , i took the wrong program , i want to do the update offline  and i took  wufuc... my mistake .

**Comment by zeffy** [comment]
No worries! It should install fine once your other updates are installed first. Sorry for the confusion and thanks for bringing this up, I'm going to add a note to that error message that explains this in the next release.
